### ISSUE TITLE
What about UnitFormat.alias()?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#103]
Indriya `SimpleUnitFormat` defines a public method `alias()` beside the implementation of API `label()`. Although they are relatively close together, could `alias()` also make sense in the API?

**Comment by desruisseaux** [comment]
It depends: what is the purpose of `alias`?

**Comment by keilw** [comment]
It is quite rarely used to be honest, even inside `SimpleUnitFormat`, there are only one or two places, `OHM `and `CELCIUS` (where there's a special Unicode character "℃" but it can also be written as "°C" with two separate characters). As it's not even in the abstract base class in the RI, I think there is very little use for it. I am neutral, but there's only been one vote from someone outside the JSR last year.

**Comment by desruisseaux** [comment]
One question: I presume that aliases would be taken as synonymous of a given unit at parsing time. I presume that at formatting time, aliases would take no role? (i.e. the "primary" symbol is formatted). Or is `UnitFormat` expected to use aliases at formatting time too?

**Comment by dautelle** [comment]
alias has its purpose: To support synonyms for a unit.

**Comment by keilw** [comment]
Not at formatting but at parsing time. If those formatters supporting it had a pattern or option for that, if could also use the alias if available for formatting.

**Comment by desruisseaux** [comment]
I have no objection against an `alias` method in `UnitFormat` but I would like to see this proposal augmented with a javadoc (not only a method signature) detailing at least the following points:

* The purpose of this method.
* How this method differ from `label(Unit, String)`.
* Whether this method is expected to have an effect at parsing or formatting time.
* Restriction on the set of legal characters (if there is any such restriction).
* What happen if the given alias is already used by another unit.

**Comment by thodorisbais** [comment]
Thumbs up from my side as well. An `alias()` method should go along together with `label()` method. That said, they should both be defined here (in our API). By the time one provides a label to a Unit they might also feel like providing some alias(es) as well, so, we shouldn't create any confusion by separating those two methods.

A more extensive view of mine can be found [here](https://github.com/unitsofmeasurement/unit-api/issues/185#issuecomment-475990158).

**Comment by keilw** [comment]
@thodorisbais Seems you were the only expert or contributor who really gave a thumbs up? Looks like we'll keep this in `SimpleUnitFormat` for now.

**Comment by thodorisbais** [comment]
Good to know, @keilw , because I was just about to start with #188 . As discussed, let's try finalizing everything on time :-)

**Comment by keilw** [comment]
I'm afraid there was not enough momentum. We might discuss the best option for the whole "mix" issue, there's been a few discussions on the mailing list, but it also is unlikely to go into the API any time soon.
