### ISSUE TITLE
Formatting Prefix?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#104]
Although often combined with a Unit, would it make sense to format Prefix on its own?

http://www.learner.org/courses/learningmath/measurement/session3/part_a/working.html shows, MetricPrefix has "aliases" or local variations of the name. Although `UnitFormat.alias()` or `label()` for a `Prefix` might also work , they are both locale or culture-agnostic. While special UnitFormat implementations that take the `Locale` into consideration may format both `Unit` and `Prefix` for a particular language or locale, too. As implementations of `UnitFormat` already use the `Prefix`, it feels like a good place to keep formatting prefixes there if done explicitly and not just internally.

Requires #103
Requires #101

**Comment by keilw** [comment]
Although we could add something plain like `getDisplayName()` for `Prefix `that might show "Kilo", it may not make much sense outside the context of a `UnitFormat` implementation. There a long name like "Kilogram" or (if i18n applies) "Kilogramm" (for `DE`) would be the logical consequence although formatting the prefix alone also makes sense. And e.g. "Centi" vs. "Zenti" there are localization issues here, too.

**Comment by thodorisbais** [comment]
I was just looking at it! Cool, one issue less!
