### ISSUE TITLE
Fix javadoc.io badge

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#109]
Unfortunately the `javadoc.io` badge is broken for milestones like "EDR", the image is messed up although the link would work.

Removing 
```
[![javadoc.io](https://javadocio-badges.herokuapp.com/javax.measure/unit-api/badge.svg)](https://javadocio-badges.herokuapp.com/javax.measure/unit-api)
```
for now.

**Comment by thodorisbais** [comment]
Are we sure what we want to add exists?
I'm trying to add locally the badge @keilw fore-mentioned, but I'm getting a 404.
