### ISSUE TITLE
module-info in java/measure directory: is it an error?

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#113]
The `module-info.java` is currently located in the `api/src/main/java/java/measure/` directory, i.e. in the `"java.measure"` package. But `module-info.java` are supposed to be located in the root package. Is it an error, or is it intentional through a particular configuration of the Maven project?

**Comment by keilw** [comment]
It's intentional, see https://github.com/JavaMoney/jsr354-api/tree/master/src/main/java in JSR 354.

**Comment by desruisseaux** [comment]
Can you elaborate? This is illegal for `javac`. Is there a particular configuration in the Maven `pom.xml` doing some magic, e.g. moving that file to the right place before to compile?

**Comment by keilw** [comment]
This was modeled after what @atsticks did for projects like Tamaya or JSR 354 making them use the module-inf but still run under Java SE 8. The "magic" must be done in those particular Maven plugins, and the build works plus all downstream artifacts recognize them properly, so there is no need to change this unless a different set of plugins is properly working.

**Comment by keilw** [comment]
Actually this is a rather common pattern, JSON-P now a Jakarta EE project: https://github.com/eclipse-ee4j/jsonp has a "jdk9" folder only containing `module-info` under  https://github.com/eclipse-ee4j/jsonp/tree/master/api/src/main

**Comment by desruisseaux** [comment]
Will do tentatively after ApacheCon at the end of September. May address multi-jar (#114) in same time since they would both use the same directory.

**Comment by keilw** [comment]
Ok, take your time, I made a link between them for Waffle. 
JSR 354 uses the toolchain plugin which makes it work, as long as the JAR works perfectly fine from Java 8 to anything newer, feel free to change it similar to JSON-P.

**Comment by desruisseaux** [comment]
What is the purpose of the `generate-module-info` goal in `moditect-maven-plugin` plugin? Why auto-generating if we provide `module-info` explicitly? This goal appears twice: once in a "modGen" profile and once in an plugin that seems to be for Eclipse.
