### ISSUE TITLE
Add badge for SonarCloud

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#117]
Add a SonarCloud badge to the README file

Needs #111 
Needs #118

**Comment by Daniel-Dos** [comment]
Hi @keilw , 

which badge would be ideal for display?

**Comment by keilw** [comment]
@Daniel-Dos Are there multiple choices?

**Comment by Daniel-Dos** [comment]
yes, 

https://sonarcloud.io/dashboard?id=javax.measure%3Aunit-api

**Comment by keilw** [comment]
@Daniel-Dos Any idea how to address the silly and ridiculous metrics? There is no way the default methods like `getSymbol()` in `Prefix` implementations could be done differently. The metric is just wrong and should be ignored.

**Comment by keilw** [comment]
See #118 please adjust the metrics or ignore wrong errors (I believe Sonar does, but I did not see it at first in SonarCloud) before we irritate people with a badge.

**Comment by keilw** [comment]
@Daniel-Dos Keep in mind, it's not a MarkDown badge there. I added two, please suggest a few others you find useful.

**Comment by Daniel-Dos** [comment]
Hi @keilw ,

wonder . 

thanks .

**Comment by keilw** [comment]
I may slightly rearrange them to contain the same type of semantics in blocks, but the amount of information looks good, thanks.

**Comment by Daniel-Dos** [comment]
thanks .
