### ISSUE TITLE
Could we add a name to ServiceProvider?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#122]
Right now, if you combine different modules that come with their own ServiceProvider, the only way to find out a particular one is via something like 
``` java
 for (ServiceProvider provider : ServiceProvider.available()) {
     if ("DefaultServiceProvider".equals(provider.getClass().getSimpleName())) {
         defaultProvider = provider;
         break;
     }
 }
```
You need to know the actual `class` sometimes hidden in the `internal` part of a library or module.

Even if the same string may be used in some cases, having a `getName()` method on the `ServiceProvider` itself would make it easier to distinguish them and find the desired provider.

**Comment by desruisseaux** [comment]
Alternatively we could use the name of the module defining the service provider. This can work even in Java 7 if we use the automatic module name specified in `MANIFEST.MF`. An advantage is that the module name is guaranteed to be unique. An inconvenient is that this approach assumes there is only one service provider per module.

Another alternative is to define an annotation instead than a method. For example:

```
@ProviderIdentification(name = "MyProvider")
class MyProvider implements ServiceProvider {...}
```

Advantage is that it allows to find the provider without initializing the class. Inconvenient is that the name must be static (can not be computed at runtime), but I don't think it is a real inconvenient in practice.

But this issue concerns all SPI in Java, not only JSR-385. Isn't an attempt to solve this issue out of JSR-385 scope? The users can still use `java.util.ServiceLoader` themselves for applying the criterion of their choice.

**Comment by keilw** [comment]
Some extensions of `ServiceProvider` actually used the `@Priority `annotation from Java standard annotations. We abandoned it in favor of a numeric value. So not sure, if an annotation really helped compared to the overhead it introduces? The idea is to know and call a provider other than the current one without having to know a particular class name.

**Comment by desruisseaux** [comment]
The advantages of annotations is that they can be inspected without class initialization. Java 9 `ServiceLoader` has a [new API for that](https://docs.oracle.com/javase/10/docs/api/java/util/ServiceLoader.html#stream()), with `Provider.type()` returning only the `Class` or a `ServiceProvider`, not the actual instance. We can read the `@ProviderIdentification` annotation on that class without triggering class initialization, i.e. without causing the JVM to execute static initializers, evaluate constant values, create a new instance of the class, _etc._ This allows to select a provider without causing the JVM to allocate resources for providers that we don't use.

After a class has been initialized, then indeed this advantage disappears.

**Comment by keilw** [comment]
That brings us to forcing Java 9 into the API for a small corner case. It seems unlikely a JSR that already started can suddenly turn into the new "iterative" model the JCP EC plans for the next iteration of the JCP itself, so for such changes (and others e.g. value types, etc.) it may require a new iterative release of the JSR at some point. Both this and #123 are convenience features, they are nice to have in 2.0, but not something crucial.

**Comment by desruisseaux** [comment]
It does not force Java 9. We can still use Java 7 `ServiceLoader` as today. The above-cited benefit of annotations would not be used with Java 7 or 8, but the API would be ready to benefit it in the future when Java 9 will become acceptable.

Furthermore if we do multi-version JAR file as proposed in #114, we can have the two worlds.

**Comment by keilw** [comment]
Some (not too many) users want to be able to use a particular provider if the current one is redefined by a module like SI, UCUM, etc. that is all they want to archive, they do not need Java 9 right now as does a huge majority of the community for at least another year or more. If this loading mechanism had a massive performance benefit, then we could do this at some point, but I would rather wait till some of `ServiceProvider `can be actually pruned in a future version of the API.

**Comment by desruisseaux** [comment]
The idea is to be ready for Java 9, even if it make no difference in Java 8. If we add a `getName()` method in `ServiceProvider`, we may have to deprecate it in the future. If we use an annotation instead, it will still work with Java 8 as well as the `getName()` method (except that the value must be static), and it will be ready for Java 9.

**Comment by keilw** [comment]
What would help https://github.com/unitsofmeasurement/unit-api/issues/123 better? I don't really see, how a user of actual code (as it works right now, see above) would benefit by using an annotation instead of a `get("providerKey")` call #123 suggests. If it helped, please advise how, or create a PR based on either of these tickets. This one is merely a helper, we could even limit it to a proper use of `toString()` it would be enough for the getter to find the desired provider.

**Comment by desruisseaux** [comment]
The annotations are not used by the users, unless (s)he want to implement his/her own discovery mechanism. The users would still use `ServiceProvider.get("something")`. It impacts only the implementation of `ServiceProvider.get(String)`.

**Comment by keilw** [comment]
Ok, as mentioned, the most minimal approach could be to override `toString()` accordingly, so a `get()` or `of()` (since it is a static factory using a string to produce an instance of `ServiceProvider` I almost prefer the latter) method can pick the right instance if it can be found.

**Comment by desruisseaux** [comment]
A standard generic annotation would be better, if we find one that do not introduce undesired dependency.

**Comment by keilw** [comment]
What about `@Named` in JSR330? I have not tried it lately, but I guess it should work similar to the `@Priority` annotation in the standard annotations module.

**Comment by desruisseaux** [comment]
This annotation seems indeed to fit the purpose. But using it would introduce a dependency to JSR-330. Similar for the `@Priority` annotation, which seems to be provided in JavaEE instead than JavaSE.

**Comment by keilw** [comment]
If it's a dependendy for Indriya or another implementation I guess we could live with that. It does not require all of CDI even if that may contain the javax.inject part now, https://search.maven.org/artifact/javax.inject/javax.inject/1/jar is available separately, not an OSGi bundle, but as we don't expose it I guess that might be enough.

**Comment by keilw** [comment]
@desruisseaux I put a @Named annotation in the current snapshot of Indriya, which is also available from Bintray. No implementation seems necessary, so please if there is a way to verify that from a local fork and it works, feel free to create a PR for this ticket plus #123 (I am neutral on` get()` vs. `of()` but the latter seems more widely used for static factory methods) and even #114 if you can, since they all involve `ServiceProvider`.

**Comment by keilw** [comment]
What is `ServiceRegistry`, something in Seshat? The API should not have a dependency to things outside the JDK even if they are relatively small in that case. If all else fails we might go for either getName() or toString() (I also added an implementation to the Default provider, so both toString() and the annotation could be used in the same way) It is of lower prio, I'd say #114 should be resolved in a Java 8 compliant way, that is at least a very small safety issue, the others are nice to have in JSR 385.

**Comment by keilw** [comment]
Although Reflection may not perform as badly as it did in earlier Java versions, I'm not sure, if it's worth in this case? @desruisseaux Not sure, if find the provider without initializing the class has a huge benefit e.g. saving memory in the JVM? Whether it's worth the overhead and possible performance penalty of reflection here. We should somehow be able to measure the side-effects. For #123 I'm inclined to close this one and postpone optimizing the internal implementation till e.g. Java 9, 10 or 11 was safe as a minimal version or there's enough momentum for these versions to add a multi-release JAR in an upcoming version of the API.
