### ISSUE TITLE
How about ServiceProvider.get() or similar?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#123]
At the moment even if #122 was applied, a loop like this or similar has to be applied:
``` java
 for (ServiceProvider provider : ServiceProvider.available()) {
     if ("DefaultServiceProvider".equals(provider.getClass().getSimpleName())) {
         defaultProvider = provider;
         break;
     }
 }
```
in order to find a particular provider if more are available.  Especially if the name was defined as a distinct attribute, we could add a static method `ServiceProvider.get()` using the name/key as an argument. If a wrong name/key was entered, it seems best to throw an exception like `IllegalArgumentException` or similar (that is how enums do it)

Needs #122

**Comment by keilw** [comment]
Along the lines of other static factory methods like those in Optional we could also call it `of("providerKey")` insteaf of `get()`.

**Comment by desruisseaux** [comment]
`ServiceProvider.of` should document that it rely on `ServiceProvider.toString()`.
