### ISSUE TITLE
Add @since 2.0 javadoc annotation to all new elements

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#127]
All new interfaces should have a `@since 2.0` annotation in their class javadoc comment. All new methods in an interfaces that existed in JSR 363 should have a `@since 1.0` annotation in the method javadoc comment.

**Comment by thodorisbais** [comment]
Hi,

I'm new to this project (and subsequently, to JSR, in general :-) ).

Is this issue still valid?

I see that the latest HEAD is fully annotated (either with `@since 2.0` or with `@since 1.0`).

Regards,
TB

**Comment by keilw** [comment]
I am pretty confident, in most classes or interfaces it should be there on the type level, but it may have slipped here or there for an individual method.

Regards,
Werner

**Comment by thodorisbais** [comment]
Oh, yes, I have only checked on the type level, not on method(s) level.
So, the request is about annotating the methods that existed in JSR-363 with `@since 1.0`, right?

**Comment by thodorisbais** [comment]
I think the initial comment was meant for `@since 2.0`, instead of `@since 1.0`. So, the point is to indeed add a `@since 2.0` annotation to all the new elements (i.e. new methods, classes, etc.), right?

**Comment by desruisseaux** [comment]
The main request is to annotate new elements with `@since 2.0`. A `@since 1.0` on classes or interfaces that existed in the previous specification may help to make things clearer, but is not strictly necessary. A `@since 1.0` on methods or fields should not be needed at all, since it would be redundant with the `@since 1.0` on the enclosing class or interface.

Note that if a class or interface is annotated with `@since 2.0`, it is not necessary to repeat it for each methods. A `@since 2.0` tag is needed only in fields or methods that are new in this specification but added in a class or interface that existed in the previous specification (optionally annotated with `@since 1.0`).

Does the above seems ok?

**Comment by keilw** [comment]
In Java many of them exist, but I can't say for sure, if `@since 1.0` was done for some elements of the JDK or they started with e.g. 1.1.

**Comment by thodorisbais** [comment]
Thank you @desruisseaux, it became more clear after you thorough explanation.
(Let's see whether my upcoming PR will depict the fore-mentioned statement 😂 )

**Comment by thodorisbais** [comment]
I believe this one can now be closed, too, given the latest commits.

**Comment by keilw** [comment]
Ok thanks
