### ISSUE TITLE
Define a Measurement Level or similar

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#130]
Based on discussions in #95 and related tasks in the RI like https://github.com/unitsofmeasurement/indriya/issues/128 the API should be aware of a `MeasurementLevel`.  The term is the most commonly used, also see [Wikipedia](https://en.wikipedia.org/wiki/Level_of_measurement) and blends in very well with the "javax.measure" package or certain elements starting with "Measurement*".

Needs #95

**Comment by keilw** [comment]
Unless we come across needs for additional values the enum (can't think of anything better here) should contain the best-known classification with four levels, or scales, of measurement: `nominal`, `ordinal`, `interval`, and `ratio` by Psychologist Stanley Smith Stevens.

**Comment by desruisseaux** [comment]
Fine for me. On a minor topic, shouldn't we use `LevelOfMeasurement` instead of `MeasurementLevel` name? A search on Google gives:

* "Measurement level": 180,000 hits, with the first hits not all related to what we mean, and for those that are what we means the actual text on those page said "Level of measurement".
* "Level of measurement": 24,100,000 hits.

**Comment by keilw** [comment]
MeasurementLevel would blend in better with top level elements in the API (assuming it gets used by either Unit or Quantity that is the only natural package) like MeasurementException, but I am not too biased on that. While e.g. UCAR calls it UnitSystem we called the same SystemOfUnits for a somewhat similar reason. So we are flexible, let's do a very quick poll and stick to it. 

If we require additional levels, could also be later, the more recent https://en.wikipedia.org/wiki/Level_of_measurement#Chrisman's_typology_(1998) sounds like a good extension to the original four.

**Comment by keilw** [comment]
A) `MeasurementLevel`

**Comment by keilw** [comment]
B) LevelOfMeasurement

**Comment by dautelle** [comment]
I believe that measurement level in English means something completely different, e.g. the measurement level of the river is 2 meters above the average.
In data science, we use a much simpler typology: [DataType](https://towardsdatascience.com/data-types-in-statistics-347e152e8bee)
For us it would be: **MeasurementType**
I propose to add a vote for this :)

**Comment by keilw** [comment]
Done, @dautelle thanks for the reference. It also contains the 4 proposed minimal types. If the group like `Categorical` or `Numerical` was of any help (IMO we at the very least need the two Numerical ones) something like that could be an additional sub-enum or other kind of attribute. I added option C and also voted (since you also voted in more than one ;-)
The JDK and other APIs also know plenty of "type" attributes or enums, `AclEntryType` just one that's at the very top alphabetically.

**Comment by keilw** [comment]
Well https://en.wikipedia.org/wiki/Statistical_data_type differentiates between at least 7 data types each also has a Level of Measurement column, so the question is, what level of detail do we want to provide for users of the API? The name frankly I care a bit less. Even `DataType` in the context of our API would be sufficient, and it has not been used at all in a public API even in the JDK (only some internal hidden ones like `com.sun` or `com.oracle`. So the degree of detail we wish to model and define may determine the name. IMO we should not call it MeasurementType or DataType and simply stick the 4 to 10 levels of measurement defined by various folks in there. If we agree, those 2, 3, 4 or more levels are the right classification to decide upon arithmetic functions, then we should call it something with "level", otherwise something with "type".

**Comment by dautelle** [comment]
@Werner Thanks for the link, we see appearing again "Level of measurement" :)

**Comment by keilw** [comment]
Yep, so we have to decide which of them suits for decision making in relevant operations. There would be very little overhead from an `enum`, even with some additional information, should it even be necessary like "numerical" or otherwise. Before pruning stuff the API currently is around 40kb.

**Comment by desruisseaux** [comment]
May be safer to take a small, well accepted, set on the basis that it is easier to add elements in the future (if desired) than removing them. Steven's 4 `LevelOfMeasurement` seems the best-known classification, and is sufficient for JSR-385 needs.

**Comment by keilw** [comment]
Although not for JSR 385 AFAIK (if @otaviojava and I talk to the EC tomorrow about the progress of the JSR I'll try to ask that) if there is an update that goes beyond a MR, we would also try to file it as "iterative" JSR next, see JSR 387 which just started its [PR]( https://jcp.org/aboutJava/communityprocess/pr/jsr387/index.html). I don't think a JSR that started could be turned "iterative", otherwise we may consider that for 385 already.

**Comment by otaviojava** [comment]
I like ¨LevelOfMeasurement¨, maybe just remove the ¨of¨ to **LevelOfMeasurement**

**Comment by keilw** [comment]
@otaviojava Thanks, but how are the two different, or would you suggest `LevelMeasurement`? I guess that short cut may cause similar difficulties and misconceptions @dautelle claimed about `MeasurementLevel`.
