### ISSUE TITLE
LevelOfMeasurement.isGreaterThanOrEqualTo duplicate standard API

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#141]
The following method has been added in `LevelOfMeasurement`:

```
public boolean isGreaterThanOrEqualTo(LevelOfMeasurement other);
```

But all `Enum` in Java are already comparable. A call to `A.isGreaterThanOrEqualTo(B)` is equivalent to `A.compareTo(B) >= 0`. Consequently do we really need that method?

**Comment by keilw** [comment]
As ordinal() is commonly used in `compareTo()` based on JavaDoc, it seems safe to rely on that for now.
A similar question could of course arise to several similar methods in `ComparableQuantity`, except `isEquivalentTo()` which has a special purpose where simple equals() is often insufficient to make a true comparison.

**Comment by desruisseaux** [comment]
I'm not sure to understand - both `compareTo` and `isGreaterThanOrEqualTo` are based on `ordinal()`. So I'm still missing the plus value of `isGreaterThanOrEqualTo`?

**Comment by keilw** [comment]
I am writing unit tests to ensure that is met by compare, then it could replace the isGreater method.
