### ISSUE TITLE
Swap isitmaintained badges with Indriya

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#143]
The "isitmaintained" badges here have less meaning, because the API/Spec discussions often end up in a longer thread instead of brief reaction to a bug or question.

**Comment by thodorisbais** [comment]
So, if I got it right, the interpretation of "swap" here is that we still keep the `Planning` section in both ( = `unit-api`, `indriya`), but with the following structure:

- `unit-api` should contain `open issues`, `closed issues`, `open pull requests`, `closed pull requests`
- `indriya` should contain the `isitmaintained` badges

Right?

**Comment by keilw** [comment]
Yes thanks. We could still add some badges to unit-api later, but currently it is more important to improve code coverage so the existing ones look better.

**Comment by thodorisbais** [comment]
Clear, good to know.
