### ISSUE TITLE
How to retrieve a Quantity from an Unit?

### ISSUE THREAD

**Issue by splatch** [unitsofmeasurement/unit-api#145]
I have fairly basic trouble which I can not solve right now with 1.0.x APIs and so far I'm not certain if its available in 2.x.

I have a necessity to extract quantity of `Unit` from an instance. Currently, if I have for example an instance of `Units.TESLA` I have no simple way to retrieve `MagneticFluxDensity` which is Quantity type. I would appreciate your tip - how such retrieval should be done.

Cheers,
Lukasz

**Comment by keilw** [comment]
Lukasz,
Thanks for raising this. I'm afraid, that is a general problem of Java that Oracle/Sun so far did not cover as well as a few other languages (e.g. Kotlin or C#, etc.) https://stackoverflow.com/questions/879855/what-are-reified-generics-how-do-they-solve-type-erasure-problems-and-why-cant

The only way you would get that is by passing the class explicitly, which some methods like `getUnit(Class)` in `SystemOfUnits` does, or the `asType` methods. We cannot fix that in 2.0, it requires language changes, maybe part of the "Valhalla" project in OpenJDK, so we keep it on our radar and might offer either a MR or follow-up release if Java itself is ready.
