### ISSUE TITLE
Prefix method names with lowercase letter?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#165]
As proposed in #164 @thodorisbais proposes to use lowercase letters for prefix methods in Prefix implementations like `MetricPrefix` or `BinaryPrefix`.

While it complies with general Java naming conventions, the RI (between JSR 108 and 275 also the API) and other implementations all use **UPPERCASE** names for methods and if based on enums the actual `enum` values. 
The idea of this was, that although a method, it represents a constant factor, thus the method itself was written like constant names in Java.

Instead of

    Unit<Pressure> HECTOPASCAL = HECTO(PASCAL);
    Unit<Length> KILOMETRE = KILO(METRE);

It would look like

    Unit<Pressure> HECTOPASCAL = hecto(PASCAL);
    Unit<Length> KILOMETRE = kilo(METRE);

Shall we change that or not?

**Comment by keilw** [comment]
A) Change the method names to lowercase characters

**Comment by keilw** [comment]
Thanks everyone. Let's see what those who were in the EG since JSR 108 (which first introduced the uppercase method names) like @dautelle or @desruisseaux think about it, but we should be able to come to a conclusion here more quickly than other topics ;-)

**Comment by desruisseaux** [comment]
I'm neutral. Both arguments for A and B have merit.

**Comment by keilw** [comment]
Thanks, at the moment I'll also wait what others think. Let's see what @dautelle thinks about it. JScience (4 mostly via JSR 275 to some extent 5) also used the uppercase version. So backward-compatibility is an argument.

**Comment by dautelle** [comment]
Voted A: Coding standard specifies that static final constant should be uppercase.
Even, if in that case it is a method, I think that rule supersedes the method name in lowercase rule.

**Comment by keilw** [comment]
Thanks for the participation. Then I also voted for A which has all Spec Leads voting. I recall the idea was that it represents a constant value, therefore the method name is upper-case. As the `enum` and method can be told apart because they are two different types, it also is not a real problem having the same name for both. Still leaving it open a bit, but wherever there should be a deadlock or undecided vote, the Spec Leads help to make the decision and if all 3 agree on a particular option, it is usually a decision-maker.

**Comment by keilw** [comment]
It was a slightly more "extended review" of the PR (which if B had been the preferred choice we could have reopened) if you want in a situation like that where backward compatibility among other things is involved. Thanks for bringing it up anyway, we had a lot of fresh ideas from EG members and contributors alike that got e.g. the `MetricPrefix` back into the API again ;-)
