### ISSUE TITLE
Fix Codacy coverage

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/unit-api#171]
Our Codacy coverage is not properly setup. We need to take a look at it.

https://app.codacy.com/project/unitsofmeasurement/unit-api/dashboard

**Comment by thodorisbais** [comment]
I see that this one was closed a bit early, wasn't it? Our current Codacy coverage is still not properly set up. In addition, we've lost the issues breakdown (there were around 50 issues listed before):
![screenshot 2019-02-03 at 14 59 04](https://user-images.githubusercontent.com/5684688/52177647-54b91600-27c4-11e9-923a-e54c4eaac2d0.png)

I suspect this implies @keilw is working on setting everything up from scratch, but I would suggest to reopen this until we have a concrete solution.

**Comment by keilw** [comment]
Not really, hard to say, why it looks that good now, but we also have Sonar set up with a similar result: https://sonarcloud.io/dashboard?id=javax.measure%3Aunit-api. It shows a few smells, 2 duplicate blocks, but nothing dramatic either.

**Comment by keilw** [comment]
@thodorisbais Did you create another project for the same codebase? https://app.codacy.com/project/unitsofmeasurement/unit-api_2/dashboard It looks like that grabs issues that don't show in the first one any more. Could we consolidate them?
