### ISSUE TITLE
Renaming Unit.compound() to Unit.mix()

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#184]
I know, this is a bit late, but better now than after the Final release.

If you search for **"compound unit"** in Google, all major findings point to an alias for "derived unit", see 

- http://wtmaths.com/compound_units.html
- https://www.wyzant.com/resources/answers/200135/what_is_a_compound_unit_maths.

As opposed to **"mixed unit"** which is explained in many places like 

- https://www.cimt.org.uk/projects/mepres/book8/bk8i18/bk8_18i3.htm
- https://www.onlinemathlearning.com/convert-unit-measurements.html
- https://youtu.be/0sRe0wPqYg0
- https://youtu.be/otRdG71tqgQ
- https://www.ixl.com/math/grade-5/convert-metric-mixed-units.

It also matches the definition by Wolfram: https://reference.wolfram.com/language/ref/MixedUnit.html

Should we rename the term "compound" with "mix" and (in the RI) subsequent classes like `CompoundUnit` into `MixedUnit`?

**Comment by desruisseaux** [comment]
I'm fine with "mixed" instead than "compound". But I have missed the discussion where `compound` method has been added into `Unit`. What was the rational for considering this feature as part of `Unit` instead than `UnitFormat`?

**Comment by keilw** [comment]
It is used primarily by `UnitFormat` or `QuantityFormat` implementations, but to model, format or parse them properly without losing information (e.g. the order of each unit/value pair within that group) it ended up being an adapted implementation of what we originally discussed. e.g. `MixedQuantity` is a true extension to `Quantity` which behaves exactly like other quantities, but it holds the list of individual values that make it up. The ideas and concepts are largely based on https://reference.wolfram.com/language/ref/MixedUnit.html (thanks I think @andi-huber pointed us there) so something like
`UnitConvert[Quantity[3.2, "Days"], MixedUnit[{"Days", "Hours", "Minutes"}]]`

should also be possible, although I'm not entirely sure, if it was implemented so far.

**Comment by desruisseaux** [comment]
But it seems to me that "3.5 days" or "3 days 12 hours" is the same quantity; only the representation is different. In the same way that "2018-01-01" or a date using Julian days is the same date; only its representation differ. After a date has been parsed, there is no information in `java.time` telling "I was written as year-month-day".

I do not question the idea of "mixed unit". I question only its presence in `Unit` interface while I think it belong to `UnitFormat` or `QuantityFormat`. Putting this method un `Unit` interface brings new problem. What would be the `Number` returned by `Quantity.getValue()` in the quantity unit is a mixed unit?

**Comment by keilw** [comment]
The combined proper value of all the "sub-quantities", the internal structure (which is necessary to preserve, even if it was completely hidden in private classes that have no value of their own) is returned. In addition it has a `getValues()` array method for the individual values.
`MixedQuantity `cannot exist without `MixedUnit`, it has to know the order and position of the sub-units.

**Comment by desruisseaux** [comment]
Looking at `testTimes()`:

```
Unit<Time> compUnit = Units.DAY.compound(Units.HOUR);
Number[] numList = {3, 12};
Quantity<Time> t1 = Quantities.getCompoundQuantity(numList, compUnit);
assertEquals(BigDecimal.valueOf(3.5d), t1.getValue());
```

The consequence is that `t1.getValue()` returns the value in `Units.DAY`, not in `compUnit` which is (I presume) the unit of `t1`. Do we have an inconsistency here?

**Comment by keilw** [comment]
Because `compUnit` requires an array not a single `Number`. I don't see that as inconsistent, the value in the "leading" unit (first of the array/MixedUnit) is returned.
Where necessary MixedQuantity requires implementation notes in the JavaDoc of getValue() otherwise it seems fine, not inconsistent. It would be more of an "alien" if it followed the old approach of a separate class not related to `Quantity `at all IMO.

**Comment by desruisseaux** [comment]
Do we have an agreement on the following points?

1. Before the addition of "mixed units" in `Unit` interface, a `Quantity` contract was that the `Number` returned by `getValue()` is in the unit of measurement represented by `getUnit()`.
2. Following sentence: _"the value in the "leading" unit (first of the array/MixedUnit) is returned"_ means that the value is no longer in the unit returned by `getUnit()`, but in another unit (even if "leading").

Another question: what would be result of `A.getConverterTo(B)` when A or B is a mixed unit? Are we suppose to take only the "leading" unit of the mixed unit? If yes, it makes a second case where "mixed unit" does not fit well in `Unit` and `Quantity` interfaces.

Last question is: which problem are we trying to solve exactly? Are we trying to store somewhere an information about how to unit were formatted? If so, why formatting information would need to be associated to `Unit`? `Number` or `java.time` keep value and formatting information separated, why `Unit` needs to be different?

**Comment by keilw** [comment]
A.getConverterTo(B) is currently based on the leading unit, which is why conversion of a `MixedQuantity` is consistent. The idea is not just about formatting and parsing, although it helps, the two are like `TemporalUnit` and `TemporalAmount` if you take `java.time.temporal`. Value and formatting information are separate here, too, which is why these elements became necessary.

**Comment by desruisseaux** [comment]
Having "`A.getConverterTo(B)` consids only the leading unit" may be consistent with "`Quantity.getValue()` considers only the leading unit", but this is not consistent with the following:

* `getValue()` returns a value in the unit of `getUnit()` (which is not the same as "the leading unit of `getUnit()`).
* `A.getConverterTo(B).isIdentity()` were A and B are of the same `Quantity` type implies that A is the same unit than B.

Do we agree that mixed units in `Unit` interface are in contradiction with the above two points?

`TemporalAmount` has many fields, but they are working in the context of a calendar which is much more complicated than what we have (variable number of days per month, bissextile years, timezones, etc.). Their purpose is not to said "I have been parsed from a date written in a particular way". So what is the purpose of mixed unit in `Unit` interface? (again I do not question the usefulness of mixed units - it is their definition in `Unit` instead than `UnitFormat` interface that I question).

**Comment by keilw** [comment]
While there's some timezone aspect that adds a complication to Date/Time, otherwise its assumptions are oversimplified. E.g. the possible TemporalUnit implementations are restricted to just a small number in an enum, this won't work for this JSR which is extendable by design. `TemporalUnit` even has a major design flaw as it prevents any other implementation, it returns the concrete `Duration`.

If you want the model of a `MixedUnit` and more importantly `Quantity` (formatting a `MixedUnit` with `UnitFormat` is possible but far less relevant) in the subsequent formats, you end up storing all sorts of data in the format implementations which you said we should avoid.


Mathematica/Wolfram has a focus on calculation, I don't see any `UnitFormat` or similar format in its reference but aside from the `MixedUnit` it defines a [MixedMagnitude](https://reference.wolfram.com/language/ref/MixedMagnitude.html) which is essentially an array of numbers. Although we went as far as a a somewhat similar wrapper in JSR 354 (`NumberValue`) there was no need for that in the Unit-API so far. Hence an array or list of numbers meets the needs on the Java platform and
`Quantity[MixedMagnitude[{1, 2}], MixedUnit[{"Feet", "Inches"}]]` 
can be done like
`Quantities.getMixedQuantity({1, 2}, USCustomary.FOOT.mix(USCustomary.INCH))`

**Comment by keilw** [comment]
And while `Units.DAY.getConverterTo(Units.DAY).isIdentity()` returns `true`, 
`Units.HOUR.mix(Units.MINUTE).mix(Units.SECOND).getConverterTo(Units.DAY)` is `false`, thus nothing suggests they would be the same.

**Comment by thodorisbais** [comment]
I like it better (as "mixed unit") as well. In the beginning, I couldn't really understand what "compound" stands for, which implies that it creates some confusion. "Mixed unit" is much more discrete.

**Comment by keilw** [comment]
Thanks everyone for voting. The API change was the smaller part. Changes in the RI follow. As for conversion from a "simple" quantity to a mixed one along the lines of Wolfram's `UnitConvert[Quantity[3.2, "Days"], MixedUnit[{"Days", "Hours", "Minutes"}]]` will create more tickets for that, help is appreciated.

**Comment by desruisseaux** [comment]
I'm fine about closing this issue since it was about "compound" versus "mix" method name. But where the discussion about adding such method in `Unit` happened?

About `Units.HOUR.mix(Units.MINUTE).mix(Units.SECOND).getConverterTo(Units.DAY).isIdentity()` returning `false`: looks normal to me. But what `Units.DAY.mix(Units.HOUR).getConverterTo(Units.DAY).isIdentity()` returns?

And I ask again: what is the problem that this API try to resolve?

**Comment by keilw** [comment]
The same solved by https://reference.wolfram.com/language/ref/MixedUnit.html

**Comment by desruisseaux** [comment]
Fine for closing the issue about method name, but where is the discussion about that method in the `Unit` interface?

**Comment by keilw** [comment]
The majority of discussions should be in Indriya, this method is just a factory like `transform()`, `alternate()`, `prefix()` or `annotate()` which is currently not in the API: https://github.com/unitsofmeasurement/unit-api/issues/54 All of them are factories and strictly not operations on a unit, if you remember [JSR 108](http://jsr-108.sourceforge.net/javadoc/javax/units/Unit.html) or the somewhat related [UCAR Units](https://www.unidata.ucar.edu/software/thredds/v4.3/netcdf-java/v4.0/javadocAll/ucar/units/Unit.html) they are missing most of these factories, only `alternate()` was there in 108. They make the API more portable, otherwise it would just as well work with something like `AlternateUnit.of(Unit<?> parentUnit, String symbol)`.

**Comment by desruisseaux** [comment]
But given that the presence of this `mix` method in `Unit` interface seems more debatable than other methods (`transform`, etc.) because of implications like the unit of `Quantity.getValue()` return value, would it be possible to keep it in Indriya? It seems an Indriya implementation choice; other implementations may support mixed units in a different way.

**Comment by keilw** [comment]
We can discuss this but I would keep the discussion in Indriya

**Comment by keilw** [comment]
Actually will raise the question here, similar to Unit.annotate which IMO seems much lesser used, but if everyone who argued for Unit.mix() in this thread thought, it is so seldomly used and does not have to be portable, we could keep it out of the API.

**Comment by keilw** [comment]
I hate to reopen it, but it seems better than yet another ticket. #185 is about exposing it in the API which so far most experts who voted favor. This is to clarify the name, would either the 6 people who voted change to something else or it also shows a clear preference. If there are other suggestions you prefer please name "a few only" and lets see, how many thumbs each of them get? 
`join` or `group` were mentioned, but each proposed term has to make a case, not just throw in "let's have x create a mixed unit", that would be confusing as to what it's for.
