### ISSUE TITLE
Deprecate Unit.alternate()?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#186]
Discussing other API design aspects like https://github.com/unitsofmeasurement/unit-api/issues/185 it occurred, that `Unit.alternate()` is not used anywhere. Not even by other parts of any implementation, except in an abstract or concrete class implementing Unit. Wherever the `AlternateUnit` class is instantiated it is done via constructor or static factory `of()`, never `Unit.alternate()`.
Thus, should we keep it in the API or could it be `deprecated` for future removal?

**Comment by desruisseaux** [comment]
I'm neutral on that. Maybe before to decide, we should clarify what is the purpose of `alternate`. My understanding is that its main purpose was to define units for new dimensionless quantities. For example `RADIAN` is a dimensionless quantity, so (if it was not already defined in a unit library), it could (in theory) be defined with something like `ONE.alternate("rad")`. However current method signature does not allow the user to specify that the target quantity type is `Angle` instead than `Dimensionless`, so this method seems incomplete to me.

So does `alternate` has a purpose that I missed, or is it right that current method is incomplete?

**Comment by dautelle** [comment]
If I remember correctly, the idea was to alias units - for example unit("kg⋅m−1⋅s−2").alternate("Pascal")

**Comment by dautelle** [comment]
It should be read as "alternate name" (no change in quantity type)

**Comment by dautelle** [comment]
I would keep it because I think it corresponds to the NIST standard: "derived units with special names"

**Comment by keilw** [comment]
Thanks, guess the JavaDoc might use a reference to one of those BIPM pages, then we might keep it despite the little use.

**Comment by thodorisbais** [comment]
Thumbs down from my side. `Unit.alternate()` should be kept as is. [Again](https://github.com/unitsofmeasurement/unit-api/issues/185#issuecomment-475990158), a method's usage frequency shouldn't affect its existence in the API. 

An API needs to be there to provide all the available tooling to the developer, not to guide/restrict them on the usage of our Spec.

Agreed to the JavaDoc addition mentioned by @keilw above.

**Comment by keilw** [comment]
To be cosistent with https://github.com/unitsofmeasurement/unit-api/issues/185 this should also be deprecated and removed in a future version of the API. All arguments against `mix()` are even stronger against `alternate()`. 
Users should not be confused as why to create a `MixedUnit` via `MixedUnit.of()` or `new MixedUnit()` and although 100% of all `AlternateUnit` creations already happen via new `AlternateUnit()` or `AlternateUnit.of()` keep up an unused convenience method in the API. That would be totally inconsistent, so let's handle them the same way instead of confuse people.

**Comment by desruisseaux** [comment]
I'm neutral on `alternate`, but my understanding of above comments was that `alternate` has a documented effect on `Unit` instances: it changes the value returned by `Unit.getSymbol()`. This effect is documented in the javadoc (while it could be more explicit):

```
@param symbol the new symbol for the alternate unit.
```

Seshat does not use that method itself because it uses some shortcuts for initializing its dictionary of units. But it does not mean that users can not use that method.

I'm not against functionalities like mixed units/quantities, aliases, alternates, _etc_. But I would like to see new API not only in the form of method signature, but also in the form of javadoc stating what is the method contract: what is the effect of invoking that method (which `Unit` property/behavior change as a result of this method call). Sometime writing down such contract make us realize that the method should be in another interface, if the changes happen elsewhere than in `Unit`.

**Comment by keilw** [comment]
I would say it should be consistent.
The documentation in Unit for mix()
```
     * Returns the combination of this unit with the specified unit. Mixed
     * units can be used for formatting purposes, with an adequate list or array of {@link Number numbers} in {@link  Quantity} expressions or as a target unit specification for unit conversions.<br><br>Examples of mixed
     * units:<br><code> 
     *     Unit<Length> FOOT_INCH = FOOT.mix(INCH);<br>
     *     Unit<Time> HOUR_MINUTE_SECOND = HOUR.mix(MINUTE).mix(SECOND);
     * </code>
     * 
     * @param that
     *            the other unit to mix with this unit.
     * @return the corresponding mixed unit.
```
Is at least as extensive if not more than
```
    * Returns a system unit equivalent to this unscaled standard unit but used in expressions to distinguish between quantities of a different nature
     * but of the same dimensions.
     *
     * <p>
     * Examples of alternate units:
     * </p>
     *
     * <code>
     *     {@literal Unit<Angle>} RADIAN = ONE.alternate("rad").asType(Angle.class);<br>
     *     {@literal Unit<Force>} NEWTON = METRE.multiply(KILOGRAM).divide(SECOND.pow(2)).alternate("N").asType(Force.class);<br>
     *     {@literal Unit<Pressure>} PASCAL = NEWTON.divide(METRE.pow(2)).alternate("Pa").asType(Pressure.class);<br>
     * </code>
     *
     * @param symbol
     *          the new symbol for the alternate unit.
     * @return the alternate unit.
     * @throws IllegalArgumentException
     *           if this unit is not an unscaled standard unit.
     * @throws MeasurementException
     *           if the specified symbol is not valid or is already associated to a different unit.
```

I would like the way these are used to be consistent, not `Unit.alternate()` which is not even used anywhere right now just for the sake of it and a way to deal with mixed units other solutions like Mathematica/Wolfram also got via `MixedUnit.of()` although might seem closer to how `MixedUnit[{"Feet", "Inches"}]]` gets constructed in Mathematica/Wolfram.

**Comment by thodorisbais** [comment]
Do we still need to keep this open?

**Comment by keilw** [comment]
I think we'll close them all.
