### ISSUE TITLE
Create a Compound/Mix method in Quantity or other API element?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#190]
As suggested in #185 would you like to see something like `Number[] getCompoundValues(Unit<Q>… units)` either in `Quantity` or another API element (potentially `QuantityFactory`)?. Or in an implementation specific utility class like `Quantities` in the RI?

Needs #187

**Comment by keilw** [comment]
A) declare this type of method in the API

**Comment by keilw** [comment]
B) keep it in implementations including the RI

**Comment by andi-huber** [comment]
In case we like the idea of `MixedRadix` being a utility class in RI (or API?), it could serve multiple purposes:

1) construction: immutable and typesafe
```java
MixedRadix<Length> mixedRadix = MixedRadix.ofPrimary(USCustomary.FOOT).mix(USCustomary.INCH);
```
2) convenient quantity factory

```java

// This does not preserve the fractional parts!

// instead of this boilerplate
Quantity<Length> lengthQuantity = Quantities.getQuantity(1, USCustomary.FOOT)
        .add(Quantities.getQuantity(2, USCustomary.INCH));

// one could use
Quantity<Length> lengthQuantity = mixedRadix.getQuantity(new Number[]{1, 2});
```


3) primary and fractional value extraction
```java
Number[] values = mixedRadix.getValues(lengthQuantity); // -> {1, 2}
```
4) format generator
```java
// eg. by wrapping an existing QuantityFormat ...
QuantityFormat format = mixedRadix.formatUsing(new SimpleQuantityFormat());
String formatedOutput = format.format(lengthQuantity); // -> 1 ft 2 in
```

**Comment by dautelle** [comment]
I voted down the API because I don't agree with the proposed interface.
I think CompoundQuantity should be a sub-interface of Quantity. 
It is then easy to navigate through quantity components and extract values and units (returning native arrays is generally not a good idea as it forces the creation of new objects just to read).

```java
public interface Quantity<Q> {
     CompoundQuantity<Q> with(Quantity<Q> lower); 
     ...
}
public interface CompoundQuantity<Q> extends Quantity<Q> {
    Quantity<Q> getHigher();
    Quantity<Q> getLower();
}
CompoundQuantity<Duration> hhmmss = 
    factory.create(10, HOUR).with(
    factory.create(12, MINUTE).with(
    factory.create(34, SECOND);
```

**Comment by desruisseaux** [comment]
Hello @dautelle. What would be advantage of `CompoundQuantity` compared to computing the same values on-the-fly from an ordinary `Quantity`? To be more specific, what would be the advantage of the following:

```
QuantityFactory f = ...;
CompoundQuantity<Duration> q = f.create(10, HOUR).with(12, MINUTE);
Quantity<Duration> hours = q.getHigher();
Quantity<Duration> minutes = q.getLower();
```
Compared to:
```
QuantityFactory f = ...;
Quantity<Duration> q = f.create(10, HOUR).add(f.create(12, MINUTE));
Number[] components = q.getCompoundValues(HOUR, MINUTE);
Number hours = components[0];
Number minutes = components[1];
```

I see that the `CompoundQuantity` approach expresses components as `Quantity` instead than `Number`, but is the _"12 minutes"_ part in _"10 hours 12 minutes" really a quantity? That quantity does not represent anymore a physical property of the object being measured, but is purely an artifact of the measurement scale (the way a clock divides hours in minutes). I don't think that using `Quantity` for those subdivisions represent anything physical.

**Comment by andi-huber** [comment]
I'm voting B), because I don't see any strong reason to justify an API extension. RI can cover all the use-cases related to 'mixed-radix'.

**Comment by dautelle** [comment]
Hello Martin,
The main difference is that CompoundQuantity keep its internal components
separated (hence the operator with() instead of add()).
Making it easy /faster to retrieve the original parts. There are cases when
you don't want to convert everything to float and to keep the integer
components values.
Indeed some quantity don't have exact floating point representations, e.g.
"1 sec 100 ms" float value is 1.0999999999..)
Cheers,
JM

**Comment by keilw** [comment]
Hi, 
Thanks for the votes so far. @desruisseaux, @otaviojava and @thodorisbais (I know Filip just spoke about JSR 385 today so I won't bother him yet) could you also vote. So far it seems on the RI side and while I keep my vote to decide later (both would be fine) we should get to a decision soon. And try to file the PR after Easter, that also gives us time to brush the last edges over the holidays.

**Comment by desruisseaux** [comment]
@dautelle : thanks for the reply. But if the main difference is that `CompoundQuantity` keep its internal components separated, this difference is invisible (ignoring rounding errors for now) to user eyes, compared to calculating the components on the fly. Shouldn't it be an implementation details then?

Regarding the floating point representation issue ("1 sec 100 ms" float value as 1.0999999999..), keeping components separated is one way to avoid that, but not the only way. Other ways can be using `BigDecimal`, or storing the `Quantity` value as a ratio between two `long`. Each approach has different advantages and inconvenient, so it seems to me that the choice of an approach could be left as an implementation choice. We could just put a `getComponent(Unit<Q>...)` method directly in `Quantity` interface and let implementation provides the components as the wish: from a list of values stored directly in an implementation-specific `CompoundQuantity`, or computed from a `double`, a `BigDecimal` or a pair of `long`, etc.

**Comment by andi-huber** [comment]
@dautelle and @desruisseaux , I believe we are covering all the discussed 'mixed-radix' use-cases as well as the latest 'performance/precision' issue with the newly introduced `MixedRadix` in RI. 

To use the latest proposed method naming I believe, we can manage to properly implement `MixedRadix` to get this test working (or slightly modified). The point being, it should be easy to calculate `Number[] timeParts = mixedRadix.extractValues(endTime)` both efficiently and without loss of precision.

```java
@Test
void shouldUseEfficientArithmetic() {
        
	// given

	MixedRadix<Time> mixedRadix = MixedRadix.of(HOUR).mix(MINUTE).mixPrimary(SECOND); // 'SECOND' is the primary unit
	
	Quantity<Time> startTime = mixedRadix.createQuantity(9, 20, 0);  // '9h20min' in units of 'SECOND'
	Quantity<Time> duration = Quantities.getQuantity(30, SECOND); // in units of 'SECOND'

	// when
	
	Quantity<Time> endTime = startTime.add(duration);
	Number[] timeParts = mixedRadix.extractValues(endTime);
	
	// then
	
	assertEquals(9, timeParts[0]); // should be actually an int
	assertEquals(20, timeParts[1]); // should be actually an int
	assertEquals(30, timeParts[2]); // should be actually an int
	
}
```

**Comment by keilw** [comment]
Closing this with a solid majority for Option B.
