### ISSUE TITLE
Minor error in generating docs while building

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/unit-api#193]
![Screenshot 2019-05-12 at 23 38 39](https://user-images.githubusercontent.com/5684688/57588104-bac5df80-750f-11e9-96a4-845002ee59e0.png)

**Comment by thodorisbais** [comment]
Apparently, the end tag `</p>` can be omitted, if the `<p>` element is followed by `<ul>`. For more details, please refer to [the official docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) (Tag omission section).

**Comment by thodorisbais** [comment]
Closed with 759480fa243bb63a274635eeb05bb8a9ac5aafe1

**Comment by keilw** [comment]
Thanks, I did simplify the JavaDoc, check out the result: https://unitsofmeasurement.github.io/unit-api/site/apidocs/javax/measure/UnitConverter.html It looks OK.

**Comment by thodorisbais** [comment]
Apparently, we were performing changes at the same time :-)
I had fixed the issue with my latest commit by that time.
However, if you like the changes that are now live better than the ones introduced with the fore-mentioned commit, we can always revert it.

**Comment by keilw** [comment]
I didn't see a PR but if the push was there before 2.0-PDR got tagged, it's already in the release.

**Comment by thodorisbais** [comment]
No, it was a bit after I think, but I didn't notice the release notification. There was no PR because it was a straightforward change. No worries about not being part of the release, what is more important is that the release contains _a_  fix :smiley:
