### ISSUE TITLE
Specification: meter instead of metre

### ISSUE THREAD

**Issue by puce77** [unitsofmeasurement/unit-api#194]
The Specification proposes to use "metre" instead of "meter":
https://docs.google.com/document/d/12KhosAFriGCczBs6gwtJJDfg_QlANT92_lhxUWO2gCY/edit#heading=h.xw8d3vcow6xy

I would like to vote for "meter", however.

Reason: There is an informal naming convention to use US English for APIs.
E.g. "color" not "colour"
https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/Color.html
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/paint/Color.html

**Comment by keilw** [comment]
Thanks for the suggestion, but we strictly stick to the SI system here: https://www.bipm.org/en/measurement-units/#si-base-units The SI base unit for mass is `metre`, not `meter`. Systems like `USCustomary` in https://github.com/unitsofmeasurement/uom-systems call it `METER`, the SI standard sticks to the standard phrase and we also keep that in the spec.
