### ISSUE TITLE
Final deliverables

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#198]

**Comment by desruisseaux** [comment]
What is the deliverable content? Only one single module for the API please!!! (do what you want for the implementation).

**Comment by keilw** [comment]
No actually there is more, see Harold's forwarded mail to us (the Spec Leads)

**Comment by desruisseaux** [comment]
@keilw I see that the release at https://github.com/unitsofmeasurement/unit-api/releases/tag/2.0 has 2 Jigsaw module (base and format). Can we please rollback to a single Jigsaw module? I don't see any justification for 2 modules: it does not save memory, does not reduce dependencies, does not simplify implementation.

**Comment by keilw** [comment]
What do you mean, it's not in the JAR, that says `module java.measure`.
Those are optional profiles as seen in https://github.com/unitsofmeasurement/unit-api/issues/42 (which evolving the POM is not a requirement for 2.0) so no need to unwrap anything.

**Comment by desruisseaux** [comment]
Ah, sorry I saw `src/etc/modules/format/jdk9/module-info.java` and though that it would be the modularization to be deployed on Maven central. If this `etc` directory is only for profiles, then everything is fine - sorry for disturbing.

**Comment by keilw** [comment]
No worries, yes, it is only for optimized size in very small embedde environments. Where "base" and "format" are often the only ones they need, "quantity" would be an optional module, but the Java Module System only allows "all or nothing". Everything above that speaks for the "full profile".

**Comment by thodorisbais** [comment]
Could this be closed now (given we delivered the Final Release and the ballot was approved :-) ) ?

**Comment by keilw** [comment]
No, it was approved but the Final deliverables (mostly Spec) are still to be submitted. The binaries would be as they are in Bintray/MavenCentral, but the Spec PDF (2 versions for Implementors and Evaluators) still needs to be sent alongside all those questions.
