### ISSUE TITLE
Add a variant option when obtaining a UnitFormat from FormatService.

### ISSUE THREAD

**Issue by jfarjona** [unitsofmeasurement/unit-api#200]
It would be great to be able to obtain the variants for the formatting of units.  This is a case for UCUM to obtain a formatter that uses the print, case sensitive or case insensitive formatting (see https://unitsofmeasure.org/ucum.html).

The additional method could be:

```
UnitFormat getUnitFormat(String name, String variant)
```

Thanks for the good work!

Juan

**Comment by keilw** [comment]
Actually the 3rd optional argument constructing a `Locale` is also called "variant", so we might keep that term, but let's see what others think.
