### ISSUE TITLE
Add details about license on POM

### ISSUE THREAD

**Issue by lucasvc** [unitsofmeasurement/unit-api#204]
Current [POM indicates as license information](https://github.com/unitsofmeasurement/unit-api/blob/52877120dd92e2b8d0e97e79d7669dc32cff954b/pom.xml#L18-L22),
```
<license>
    <name>BSD</name>
    <url>LICENSE</url>
    <distribution>manual</distribution>
</license>
```

But [readme badge clearly states as BSD3 license](https://github.com/unitsofmeasurement/unit-api/commit/8f96851da6b15377bb916ce42879aef253f9df9d#diff-04c6e90faac2675aa89e2176d2eec7d8R7), leaving the POM not coherent and ambiguous (as the [BSD multiple flavours](https://en.wikipedia.org/wiki/BSD_licenses)).

So when using tools to analise licenses (i.e., [jk1/Gradle-License-Report](https://github.com/jk1/Gradle-License-Report/)) requires manual review of the corresponding license.

Maybe adding in the name a term like,
* 3-Clause
* Revised
* New

would make coherent visual documentation and POM file, moreover would help automated tools.

**Comment by keilw** [comment]
I think we can do that in the current codebase (no release planned as of now) because the detail page of the JSR also says it's "a BSD 3-Clause License". Thanks for the suggestion.

**Comment by lucasvc** [comment]
Other libraries related to the JSR 385 suffer this same issue,
* [`tech.units:indriya`](https://github.com/unitsofmeasurement/indriya/blob/master/pom.xml)
* [`systems.uom`](https://github.com/unitsofmeasurement/uom-systemsblob/master/pom.xml)
* [`tech.uom.lib`](https://github.com/unitsofmeasurement/uom-libblob/master/pom.xml)

should I open corresponding issue in each of them?
