### ISSUE TITLE
Make API page more flexible

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#205]
To make the API page more flexible, we should try to move the pages from the `gh-pages` branch to the "docs" folder in the master branch.

**Comment by sukanth** [comment]
Hey, @keilw I can help you with this. let me know what needs to be done.

**Comment by keilw** [comment]
Hi @sukanth, please have a look at how this was done in https://github.com/unitsofmeasurement/uom-systems/tree/master/docs. It is a little tricky because an admin first has to change the gh-page definition, so maybe a clean slate like https://github.com/unitsofmeasurement/uom-demos/issues/87 or https://github.com/unitsofmeasurement/uom-lib/issues/58 was better, because this project changes the API and strictly speaking only JCP members (are you?) are supposed to change that repository. This does not apply for all the others. Good question about the .JS I have not tested it, but it is also for IE6-8, even 11 is legacy now, so I would not worry too much about that.

**Comment by sukanth** [comment]
I am not sure what JCP member is? if you mean [](https://jcp.org/en/participation/members) this? I can create an account there.  I can help with the other two repositiries too.. But let's go one after the other. Lets first get this knocked out, then will concentrate on the others. Thank you. Will start working on this and create a PR today to the master.

**Comment by keilw** [comment]
Yes, and unless you joined at least as an Associate Member and got confirmed, please focus on the other two because they are not part of the JSR itself, so there are less restrictions or caution about who contributes what.

**Comment by sukanth** [comment]
@keilw Thanks, I just realized that I already have a JCP account. I Will start working.

**Comment by keilw** [comment]
Why is is not under https://jcp.org/en/participation/members/G, did they misspell your name?

**Comment by sukanth** [comment]
I am not sure .. I just used my oracle account to log in there and it allowed me in. I might have to apply for membership here https://jcp.org/en/participation/membership. will do that right away.

**Comment by keilw** [comment]
Ok but that'll take weeks, please don't worry about this repo, there are the others, if you would like to raise a PR, since this requires changing the actual metadata but it can be done at a later point.

**Comment by sukanth** [comment]
Okay, Can you assign me to those tasks/issues in the repos so that I am sure that we are talking about the same repo?

**Comment by sukanth** [comment]
https://github.com/unitsofmeasurement/uom-demos/pull/88 
https://github.com/unitsofmeasurement/uom-lib/pull/59

Hey, @keilw  worked on unitsofmeasurement/uom-demos#87 and unitsofmeasurement/uom-lib#58 please find the PR's above. Let me know if those are okay or need any changes. I just copy-pasted the whole docs folder from the other repo to these as discussed. Thanks
