### ISSUE TITLE
Improve code coverage of ServiceProvider

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#219]
At the moment `ServiceProvider` has a lower code coverage which affects the overall metrics for the project. Should be above 80% for Sonatype.
While the new annotations or also existing javax ones can be tested via extension modules or the RI there are no tests here.
Either `ServiceProvider` should be excluded from JacoCo or we get a test in here that also tests those annotations.

**Comment by Oliver-Loeffler** [comment]
Haven't been here for a while, will see what I can do.

**Comment by desruisseaux** [comment]
Note: pull request #242 (if accepted) should probably be merged before to work on test coverage.

**Comment by keilw** [comment]
With the latest PRs up to #251 the coverage has gone up to nearly 90%. We may never get to 100, but that is a pretty good improvement and also marked in green, hence closing this ticket.
