### ISSUE TITLE
Replace tabulations by 4 spaces

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#249]
The `pom.xml` file is difficult to read in editors that use 8 spaces per tabulation. Not only the code is stretched to the right, but it is also misaligned because lines using tabulations are interleaved with lines using spaces. The code would be more readable if all tabulations were replaced by spaces. It could be done easily with a script, but all pending pull requests should be merged first for avoiding conflicts.

**Comment by keilw** [comment]
It's applied via format POM, please check it out and if the file is appropriate close the ticket.

**Comment by desruisseaux** [comment]
Actually the commit has rather replaced everything by tabulations. Well, at least it is consistent now. But do we want to keep tabulations or use spaces instead?
