### ISSUE TITLE
Should we deprecate MetricPrefix.DEKA()?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#250]
While extending the prefixes based on #243 I noticed, we always used the US-spelled `DEKA()` despite an otherwise British naming `DECA()` that also correlates with the [BIPM](https://www.bipm.org/en/measurement-units/si-prefixes).
I decided to immediately fix the enum entry because it would be rather weird to have both (and break tests etc. based on the number of `enum` entries, because they would be 25 instead of 24), but keep the (far wider used, and until MR2 only one mentioned in the JavaDoc) convenience method in both the BIPM/English and US version.

The question is, do we keep both or should we deprecate `DEKA()` to be removed from a future version of the API?

**Comment by keilw** [comment]
@dautelle, @otaviojava or @desruisseaux, any thoughts? 
Given the [NIST](https://www.nist.gov/pml/special-publication-811/nist-guide-si-chapter-4-two-classes-si-units-and-si-prefixes) uses `deka` I'm inclined to keep both methods.

**Comment by dautelle** [comment]
Agree, let's keep it :)

**Comment by keilw** [comment]
Thanks for your input. As the method is only a "convenience method" or the old style of using the prefix (before `Unit.prefix(Prefix)`) there seems no harm in having both, while the enum had to be renamed in a slightly harder change, but as the methods were around longer that should be acceptable and break few or no code.
