### ISSUE TITLE
Update Spec Document for MR2

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#253]
Add chapters for Java 17+ and using records.

**Comment by keilw** [comment]
I created this ticket for a few minor spec improvements, primarily how to use the record from Java 16 onward. @desruisseaux, @dautelle, @otaviojava or others, would you be able to check it out briefly?

**Comment by desruisseaux** [comment]
What records would be used for? Would it be adding examples in the documentation about how JSR 385 could be implemented with records, or is this issue about changes in JSR 385 API?

**Comment by desruisseaux** [comment]
No problem for RI, demo or documentation. For the API itself, even if on my side I'm on Java 11, there is a lot of software that are still on Java 8. So I guess that the API needs to still Java 8 compatible for a few more years. But only the API, the rest can move on.

**Comment by keilw** [comment]
For MR2 the RI should also stick to Java 8. It may also start using Java 11 in a future version, but only a few minor 2.x digits down the road. As the RI should be closer to the API than other implementations, I guess Multi-Release-JARs work fine for Indriya.
