### ISSUE TITLE
Javadoc corrections

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#36]
This issues list some Javadoc statements that may need to be fixed.

### ServiceProvider.getQuantityFactory(Class)
Javadoc said _"Return a factory for this Quantity"_. I think that we mean _"Returns a factory for the given Quantity type"_. Also the javadoc for the `@param` tag should be _"the quantity type"_.

### Quantity.divide(Quantity)
Javadoc said _"Returns the product of this Quantity divided by the Quantity specified"_. I guess that we mean _"Returns the quotient ..."_.

### SystemOfUnitsService.getSystemOfUnits(String)
Javadoc for `@return` tag said _"the given system of units"_. I think that we mean _"the system of units for the given name"_.

### Unit.alternate(String)
`UnitFormat.label(String)` said that it throws an `IllegalArgumentException` for illegal symbol, but `Unit.alternate(String)` does not said what happen in such case. I presume that in the `@throws` tag, the _"if the specified symbol is already associated to a different unit"_ statement could be replaced by _"if the specified symbol is not valid or is already associated to a different unit"_.

### QuantityFormat.parse()
Parses a portion of the specified CharSequence from the specified position to produce an object.
Should be "... to produde a quantity." in both cases

**Comment by keilw** [comment]
### UnitFormatService.getUnitFormat(String)
`UnitFormatService.getUnitFormat(String)` states "...For example getUnitFormat("UCUM") to return a UCUM specific UnitFormat implementation."
It should refer to "Simple" instead, because UCUM related formatting is not part of the RI and therefore out of scope for the JSR itself.

**Comment by Oliver-Loeffler** [comment]
I need to read here a little.

**Comment by Daniel-Dos** [comment]
HI,

how I can help here ?

**Comment by keilw** [comment]
See above, the snippets and remedies are mentioned for selected API elements.

**Comment by desruisseaux** [comment]
Javadoc of `Quantity` contains in some places:

```
(<a href="#optional-restrictions">optional</a>)
```

but I see no `optional-restrictions` anchors defined in this page. What is it supposed to point to?

**Comment by thodorisbais** [comment]
Given that #158 is merged, this one can now be closed, since every item mentioned here has already been taken care of.
