### ISSUE TITLE
Java 9 support for "Full Profile"

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#41]
Loosely following patterns by JSR 374 (https://github.com/json-p/api-ri/blob/master/api/src/main/jdk9/module-info.java and profiles in https://github.com/json-p/api-ri/blob/master/pom.xml) we should add a module (based on JSR 374 it would be "java.measure") and module-info for Java 9 builds.
Effectively releasing such build or any additional Java 9/Jigsaw support will require a MR1 of JSR 363.

**Comment by keilw** [comment]
JEP http://openjdk.java.net/jeps/200 states that:

>1. Standard modules, whose specifications are governed by the JCP, must have names starting with the string "java.".

So the module name should be `java.measure` for the Full JSR 363 module.

**Comment by desruisseaux** [comment]
Added a pull request for partial support (not yet fully working because of changes needed in `maven-compiler-plugin` and other Maven plugins): https://github.com/unitsofmeasurement/unit-api/pull/51
