### ISSUE TITLE
implement Serializable

### ISSUE THREAD

**Issue by BigMichi1** [unitsofmeasurement/unit-api#43]
Hello,

it would be really nice if the API implements Serializable so that Quantity and Unit can be transfered over the wire

**Comment by keilw** [comment]
Hi,
Thanks for your suggestion. There was a similar request for JSR 354 and for similar reasons (you find them explained here, e.g. Java Head Architect Brian Goetz himself kindly explained http://stackoverflow.com/questions/37866041/why-is-javax-money-currencyunit-not-serializable) we won't do this on an API level, but only in implementing classes (for Java SE, ME does not have any `Serializable`)
