### ISSUE TITLE
Rename ParserException to MeasurementParseException

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#46]
A rather generic `ParserException` can be found at least in JDK Nashorn, but otherwise both the JDK and other JSRs either call it `ParseException` (like `java.text.ParseException`) or `*ParseException` (like `MonetaryParseException`, `DateTimeParseException`, etc.) 

It is not the most urgent case, but with other proposals like https://github.com/unitsofmeasurement/unit-api/issues/39 that also would require adding a new name and deprecate the old one, it's worth do mention this as well. A new exception could be called `MeasurementParseException`.

**Comment by keilw** [comment]
Removed usage of ParserException from a format() method, so I would leave it for now, and close this one. Leaving https://github.com/unitsofmeasurement/unit-api/issues/58 open.

**Comment by keilw** [comment]
Reopened this as it would be cleaner and more consistent with JSR 310, 354 and others.

The idea would be to leave `ParserException` in the API 2.0 if we have to (for backward compatibility only) but simply extend a new `MeasurementParseException` and mark `ParserException` deprecated.

**Comment by keilw** [comment]
A) Rename `ParserException` to `MeasurementParseException` for consistency with a large number of APIs and frameworks (JSR 310, 354, Jackson, Gradle,...) marking the old one deprecated.

**Comment by keilw** [comment]
B) Keep `ParserException` as it is.

**Comment by dautelle** [comment]
Why not MeasureParseException (makes more sense and shorter) ?

**Comment by desruisseaux** [comment]
But this exception can also occur while parsing `Unit` objects instead of `Measure` objects, isn't it?

**Comment by keilw** [comment]
Yes, but `Measure` is not an API element any more, `Quantity` is. Having the base exception start with Measurement, I thought `MeasurementParseException` (similar to `DateTimeParseException` in Date/Time) would be a good name. We have a QuantityFormat interface now, so both `Unit ` and `Quantity` can be parsed, which is why `UnitParseException` won't be enough.

**Comment by keilw** [comment]
Although it is only an SPI element of Indriya, we have a `Measurement` interface ever since JSR 363, so calling it `MeasurementParseException` sounds more consequent since this exception will also extend `MeasurementException`. Compared to `IncommensurableException` it is just one more character ;-)
