### ISSUE TITLE
Apply changes to Base Units in JavaDoc

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#57]
Especially in the JavaDoc of SI Base Quantities the upcoming [changes to the SI](http://www.bipm.org/en/measurement-units/rev-si/) should have an impact.

**Comment by keilw** [comment]
https://www.nature.com/news/si-units-need-reform-to-avoid-confusion-1.22417

**Comment by thodorisbais** [comment]
Point is, what needs to be updated exactly? I mean, take `Time.java` docs as an example:

<pre>
Period of existence or persistence. The metric system unit for this quantity is "s" (second).
</pre>

What needs to be updated here?
Do we need to add the definition of `s` as well? Something like that maybe?
![screenshot 2019-01-24 at 23 14 36](https://user-images.githubusercontent.com/5684688/51712034-e212a280-202d-11e9-9c6a-1c5c3f3cfcf0.png)

I think an example here might help.

**Comment by keilw** [comment]
Yes, the JavaDoc in many cases and the Spec document in some.

**Comment by thodorisbais** [comment]
Given that the requirement contains no example, I took the liberty to open a (sample) PR (#168 ) for `Time`, as I fore-mentioned, so that we have at least a visual example to compare it to our actual needs. I would be interested in your views, as mentioned in the PR.

**Comment by thodorisbais** [comment]
Closed with #173 and #172
