### ISSUE TITLE
Provide a more general purpose MeasurementFormatException

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#58]
Right now the API defines only `ParserException` for many errors in the context of parsing or formatting. Sometimes the information available does not meet all arguments `ParserException` may take like the exact position of a parsing error. If a problem occurs when formatting, ParserException sounds a bit misleading. Ideally a format-related but more general purpose exception should be introduced. Something like `MeasurementFormatException` or similar. The current `ParserException` could extend such exception.

Also see https://github.com/unitsofmeasurement/unit-api/issues/46

**Comment by keilw** [comment]
Having `MeasurementParseException`, I'm not sure, if we need an equivalent like `MeasurementFormatException`, thoughts?

**Comment by dautelle** [comment]
I don't think it is a good idea to sub-class,  it is a parsing error (not an unit or measurement error)

**Comment by keilw** [comment]
Thanks, if there are no cases where formatting needs a dedicated exception, then we already got one for parsing errors.

**Comment by thodorisbais** [comment]
Thumbs up from my side. In case we agree to go forward with this one, we need to also keep in mind [some remnants/logistics](https://github.com/unitsofmeasurement/unit-api/issues/46#issuecomment-374617081) from #46 .

**Comment by keilw** [comment]
Similar to the Money and Date/Time JSR (aka java.time) there is a specialized `…ParseException` which we started calling `ParserException`, to tell it apart from other more general frameworks this was renamed, but there seems to be no need for a `...FormatException `at this point.

**Comment by thodorisbais** [comment]
Cool!
