### ISSUE TITLE
Retrieving a unit from SystemOfUnit via String representation

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#65]
Currently SystemOfUnits allows to acces the **default** (base) unit like:
```
SystemOfUnits metricSystem = ServiceProvider.current().getSystemOfUnitsService().
   getSystemOfUnits();
Unit<Length> metre = metricSystem.getUnit(Length.class);
```

For other units it is necessary to look it up from the set of units
```
Unit<?> metre;
SystemOfUnits metricSystem = ServiceProvider.current().getSystemOfUnitsService().
   getSystemOfUnits();
for (Unit u: metricSystem.getUnits()) {
  if ("m".equals(u.getSymbol()) {
    metre = u;
    break;
  }
}
```
Although this `for` loop may be easier and shorter with Lambdas would it make sense to add a method like `<? extends Unit<?>> getUnit(String key)` to `SystemOfUnits`? Allowing to access a `Unit` via its `String` representation. Whether symbol, name or label (what's used by `toString()`) is a separate question, first we should decide, if we want this extra method in the 2.0 API.

**Comment by jhg023** [comment]
Depending on the quantity of units, would it be viable to map a unit's `String` representation to itself (either via hashing or with some immutable radix tree implementation) for potentially faster access (if that method were to be added)?

Also, if a `getUnit(String)` method *is* added, then I assume an appropriate `UnitNotFoundException` or `UnitDoesNotExistException` must be added with it.

If opinions from the community are taken into consideration, then I'm all for it 👍

**Comment by keilw** [comment]
Thanks for the quick response. Community input is very welcome. Those who wish to contribute further e.g. via a PR must either join the JCP as Full or Associate member, depending if they want to join as Expert or Contributor (PR is usually fine for either) You are right, that if the string does not match available units either `null` could be returned (that's the usual `Map` behavior) or an exception thrown. If we need a special exception, an existing one like `MeasurementException` or e.g. `IllegalArgumentException`, etc. could be discussed. And of course from Java 8 there is also `Optional`. We did not use it in another situation because it caused problems with the vital generic type safety, but it would be worth exploring if it could be used in this case.

**Comment by jhg023** [comment]
@keilw Thanks for the quick response as well!  Luckily I'm already a Full Member of the JCP and would love to contribute to the JSR in any way that I can.  I do agree that `Optional` would be a good contender for this case and should be taken advantage of.  However, there's still the case of someone passing `null` to the function, and `Optional.of(null)` throws a `NullPointerException`.

**Comment by keilw** [comment]
@jhg023 Thanks for the confirmation. If you are a full member and would like to help the API, please nominate yourself to join the JSR https://jcp.org/en/jsr/egnom?id=385. Full Members can chose between EG and Associate, too, I would say, if somebody is ready to do more than an occasional contribution or PR feel free to join the EG, Either way we welcome members of the Community. You are right about `null` being passed, that is already caught in most other cases, e.g. `UnitFormat.label()` etc. and we should handle it in a similar way.

**Comment by keilw** [comment]
Right now, SystemOfUnits does not strictly specify, what to return in most cases. SystemOfUnitsService however states for the getter, it "Returns the system of units having the specified name or <code>null</code> if none." This could be a possible pattern to use.

**Comment by jhg023** [comment]
@keilw Thanks for the suggestion; I'd be happy to nominate myself!  Also, seeing as you're currently compiling with Java 7, returning `null` would suffice.  If the minimum Java version ever changes, then I suppose it could be looked at further.

**Comment by keilw** [comment]
@jhg023 Happy if you joined the EG. Indriya (or prior implementations) also would sometimes return `null `e.g. if a `Dimension `is passed that has no unit, but there or in uom-se we already apply Lambdas and `Streams`.  Even with Java 8 as minimal version (the 2.0 API might do that as most other JSRs also require it now) we must remain backward-compatible so where `SystemOfUnitsService `returned null now, we have to be very careful not to break that, but in places where it has not been strictly specified, we can do so now.

**Comment by jhg023** [comment]
@keilw I just did!  I also understand how important backwards compatibility is for a JSR.   I'll make sure to keep any modifications to Java 7 standards for now.  Also, I apologize for getting off-topic, but should a suggestion be submitted as a PR or as an issue (before a PR is made for discussion)?

**Comment by keilw** [comment]
In `SystemOfUnitsService` the `getSystemOfUnits(String name)` method is specified
>Returns the system of units having the specified name or null if none.

So I think returning `null` is OK in the actual system, too.
