### ISSUE TITLE
How to retrieve multiple formats from SPI?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#66]
As the new API adds `QuantityFormat`, there could be two approaches in the SPI. 
Please vote for your preference.

**Comment by keilw** [comment]
A) Add a new `QuantityFormatService` which is more or less a duplicate of `UnitFormatService` but returns `QuantityFormat` instead of `UnitFormat`.

**Comment by keilw** [comment]
B) Add a new combined `FormatService` (or something like `MeasurementFormatService` if that feels better, although there are no similar interfaces right now in the JDK) that allows to retrieve both `UnitFormat` and `QuantityFormat` (except `getAvailableFormatNames()` there is no ambiguity right now, it could be `getAvailableUnitFormatNames()` and `getAvailableQuantityFormatNames()`). **Deprecate** `UnitFormatService` so in a future version the SPI can be simplified and the old service removed.

**Comment by dautelle** [comment]
A QuantityFormat should be easily created from a UnitFormat and a NumberFormat

**Comment by keilw** [comment]
That's exactly how the RI does it with https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tech/units/indriya/format/NumberSpaceQuantityFormat.java, but on the API level, the question is, do we want one or two separate registries? [UnitFormatService](https://static.javadoc.io/javax.measure/unit-api/1.0/javax/measure/spi/UnitFormatService.html) is just a registry for looking up implementations, it currently does not add or manipulate existing instances.
