### ISSUE TITLE
Quantity#inverse() and Unit#inverse() - Naming is ambiguous

### ISSUE THREAD

**Issue by andi-huber** [unitsofmeasurement/unit-api#73]
The intent of `Quantity#inverse()` and `Unit#inverse()` methods might be confused with meaning the 'Additive Inverse'.

In math terminology the term 'inverse' can be applied to any function, without being specific. 

The API currently uses `inverse()` as the 'Multiplicative Inverse', but is not clear about this within the java-doc.

If there's any chance to improve the API, I'd suggest:
- (For symmetry reasons) adding `Quantity#negate()` as the 'Additive Inverse' (no change in Unit)
- Replacing `Quantity#inverse()` with `Quantity#reciprocal()` as the 'Multiplicative Inverse'
- Replacing `Unit#inverse()` with `Unit#reciprocal()` as the 'Multiplicative Inverse'

Cheers, Andi!

**Comment by keilw** [comment]
Hi,

+1 for potentially adding `Quantity.negate()` similar to a matching method in `BigDecimal`.
If necessary back it by `Unit.negate()`, too.

About inverse() vs. reciprocal(), we have to discuss this among EG and contributors. There is no such thing in the JDK, but e.g. Apache Commons Math does offer a similar method under the same name: 
http://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/util/BigReal.html#reciprocal()

Note, the JavaDoc also states: `@return the inverse of this.`
Which is basically the method name JSR 363 and even 275 used so far.

We do have other issues like https://github.com/unitsofmeasurement/unit-api/issues/39 here, so if adding a new/different method name is justified there, we could do the same for `Unit` or `Quantity`, but the old methods must remain `@deprecated` at least for another Unit-API release (let's assume, the JCP still exists then in its current form ;-)

**Comment by filipvanlaenen** [comment]
The negate method would also simplify the implementation of the subtract methods.

**Comment by keilw** [comment]
Thanks, maybe someone could split this into a separate ticket. Adding a new method that makes sense for enough use cases is less critical than renaming/removing existing methods.

**Comment by jhg023** [comment]
I support deprecating both `Quantity#inverse` and `Unit#inverse` in favor of `Quantity#reciprocal` and `Unit#reciprocal`, respectively.  If this is a viable solution (and if someone hasn't already done this), I'd happily submit a PR with the change.

**Comment by keilw** [comment]
We have to discuss this. There's a ticket to rename/deprecate `isLinear` already, and to simplify formatting `UnitFormatService` and `Parser` have already been deprecated. It would be rather ugly to keep deprecating half of the API, but please file at least one issue to discuss it.

**Comment by keilw** [comment]
Actually this ticket as basis for discussion is enough, but for a proper standard everything must remain in **parallel** even if we added a new name.

**Comment by andi-huber** [comment]
Just for info or in case someone is wondering: 
We also have `UnitConverter#inverse`, but in this case the naming is precise, because it refers to inverting the converters transformation function, regardless of what kind of transformation this is.

**Comment by keilw** [comment]
The participants of the hangout on June 21 agreed, that both inverse() and reciprocal() are correct, also in Wikipedia, so we would prefer not to change it.

**Comment by desruisseaux** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Multiplicative_inverse) uses both "multiplicative inverse" and "reciprocal". I don't know which name is best, but apparently "inverse" is not wrong if we specify the multiplicative context. Also, given that the unit of `Quantity.inverse()` has the unit of `Unit.inverse()`, maybe keeping this parallelism is a convenient memo-technic?

**Comment by keilw** [comment]
Thanks, @andi-huber would you be happy if e.g. we also point to that Wikipedia article in the JavaDoc, but otherwise leave the method name as it is?

**Comment by andi-huber** [comment]
Thanks @keilw.
If no one else has the feeling, that the naming is ambiguous, than I'm happy to leave it at what it is, yes.

**Comment by keilw** [comment]
Thanks for the confirmation. I would leave the ticket open as long as someone added a few words and a link to that Wikipedia article. And then close it.
