### ISSUE TITLE
Use default for UnitConverter.isLinear() and isIdentity()

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#75]
Use a Java 8+ `default` method for `UnitConverter.isLinear()` and `isIdentity()`.

**Comment by desruisseaux** [comment]
Should we really provide such default method? In the collection framework, all default methods provide a default implementation that fulfill the method contract documented in the javadoc. They may not be optimal - subclasses override those default methods for providing a more efficient implementation - but not for changing their behavior.

In the case of `isLinear()`, a default implementation returning `isIdentity()` does not fulfill the method contract. A return value of `true` means that the converter is linear (okay), but a return value of `false` does not mean that the converter is non-linear. It does not seem to me that the javadoc allowed this flexibility.

**Comment by keilw** [comment]
Currently the same is done in `AbstractConverter`. At least for `isIdentity()`. Which always seems to be false except in the actual `Identity `converter class. 
If you think isLinear() may better be excluded from providing a default, please create a separate ticket.

**Comment by desruisseaux** [comment]
Filled a new issue #76. As explained in this issue, I think it is okay to have those default implementation in `AbstractConverter`. Only in Unit-API, I think we should not not provide any default method except when we can do that in a way that really fulfill the method contract. For the reference implementation, this is different for the reason explained in #76.
