### ISSUE TITLE
How to retrieve prefixes?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#85]
Based on input and concerns by @desruisseaux in https://github.com/unitsofmeasurement/unit-api/issues/83 please allow me to cast another vote to clarify how we offer `Prefix` retrieval from `SystemOfUnitsService`?

Actually [DefaultSystemOfUnitsService](https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tech/units/indriya/internal/DefaultSystemOfUnitsService.java) in the RI implementing the interface is of no value, because all the  implementations like [SISystemService](https://github.com/unitsofmeasurement/si-units/blob/master/units/src/main/java/si/uom/impl/SISystemService.java) in si-units have to do the same because it's enforced by the interface. Even if (in this case the RI already defines the only "SI Prefix") the module does not define its own prefixes. 
Either the RI must get an `AbstractSystemOfUnitsService` similar to AbstractSystemOfUnits, allowing all RI-based modules to derive from it, or the one-liner could go directly into `SystemOfUnitsService` as default method. Those can always be overriden by implementations that do not rely on enum-based prefixes, so there's nothing lost, but no implementation that uses enums would need any boiler-plate code. It is just a single line of code that every implementation can override if it has to.

**Comment by keilw** [comment]
A) Use a `Class` and either use the one-liner (`return Collections.<Prefix>unmodifiableSet(EnumSet.allOf(prefixType.asSubclass(Enum.class)));`) as default method in SystemOfUnitsService or at least a new AbstractSystemOfUnitsService so modules that have no `Prefix` of their own don't have to declare a useless method.

**Comment by keilw** [comment]
B) Use a `String` and define a new `AbstractSystemOfUnitsService` in the RI so modules that do not have a `Prefix` implementation don't have to declare or implement the methods.

**Comment by desruisseaux** [comment]
Do we really need to provide a default implementation? An implementation that do not support prefix can just return `Collections.emptySet()` - it is not unreasonable to leave that task to implementors.

**Comment by keilw** [comment]
It would be an unnecessary overhead to create that in every module like SI or Systems (which does have a few prefixes) With at least the `AbstractSystemOfUnitsService` approach similar to how ServiceProvider does it, only the modules that really do add their own prefixes have to implement something.

**Comment by desruisseaux** [comment]
If the `AbstractSystemOfUnitsService` class is only in the RI (no new interfaces in the public API), I'm neutral on that.

**Comment by keilw** [comment]
IMO that would be required in either case. Because there is no dependency on RI classes the one-liner could also be used in the API but it doesn't have to. Let's see what others vote for then.

**Comment by keilw** [comment]
@desruisseaux We reached a "critical mass" of 3 EG Members who voted in favor of A. While I understand that knowing the exact class by name adds a bit of implementation dependance, much like JSR 310 (where the API is almost irrelevant, users are encouraged if not forced to use the RI only) prefixes are in most cases used via the "mirror" functions and methods like `KILO`, `MILLI`, etc. Allowing an API level inspection is not much more than e.g. using `TemporalUnit` (an interface) instead of [ChronoUnit](https://docs.oracle.com/javase/9/docs/api/java/time/temporal/ChronoUnit.html) (also an enum) in JSR 310. While some elements of the "pseudo API" are used in `TemporalUnit` the RI element `Duration` is returned which is a hard and heavy tie-in with that RI. In our case passing the `Class` means we do not even restrict implementations to using an `enum`. Should they wish a `Map` etc. then the only restriction is having a `Class` and not `String` as the key for that map.

**Comment by keilw** [comment]
We don't restrict them to `MetricPrefix` or `BinaryPrefix` in the API, you have to pass the class as an argument. And so far we made a democratic decision what to use. I hope one or the other EG member or Spec Lead including @dautelle also gets a chance to vote on it, but I would not take it out of the API because the API is totally independent of a concrete implementation. E.g. @duckAsteroid told me when he voted, he prefers a class because it is more concrete instead of passing a string or some alias. The way we did for getSystemOfUnits, but doing it the same way here would require to cache the sets in the AbstractSystemOfUnitsService rather than calling it on-the-fly. That way a getAvailablePrefix"Something" is not needed like we do it with the unit systems or formats.

**Comment by keilw** [comment]
Beside it's exactly the same as http://unitsofmeasurement.github.io/unit-api/site/apidocs/javax/measure/spi/SystemOfUnits.html#getUnit-java.lang.Class-.

The quantity type class may or may not be one declared in the API. Whenever you create your own unit system then it could be `Acidity` or `Fitness` declared by implementations or extension modules rather than the API.

**Comment by keilw** [comment]
It's precisely the same. The special somewhat weird nature of the Enum class won't allos us to do `getPrefixes(Class <? extends Prefix>)` it just won't work, that's why you suggested the `<?>` wildcard. Other than that each of them takes a class that either extends/inherits `Quantity` in one case and a class that inherits `Prefix` in the other. Where it's defined has nothing to do with it. We could have left the whole quantity package as optional extenstion, it is also an optional package only included in certain profiles, thus even `Length` are not mandatory elements of the API. Take https://github.com/unitsofmeasurement/uom-domain/tree/master/health if you want to call `getUnit(Class<? extends Quantity>)` there you must pass` Heartbeat.class` or `HeartRate.class`, both part of the Health implementation/extension. Nothing "vendor-neutral" there either, you cannot just pass `Quantity.class` instead.

**Comment by desruisseaux** [comment]
There is nothing preventing us to use `getPrefixes(Class <? extends Prefix>)` - see the two above merge requests. But this is unrelated to the point I'm trying to do.

`getUnit(Class<? extends Quantity>)` and `getPrefixes(Class <? extends Prefix>)` are **not** the same. I can use the former in an implementation-neutral way:

```
// No explicit reference to any implementation here
Unit<Length> = system.getUnit(Length.class);
```

There is currently no way to use `getPrefixes(Class)` in such implementation-independent way, because we do not provide any standard `Prefix` subtypes. If Unit-API provides standards `Prefix` subtypes for SI and other system of prefixes, that would solve my objection. But does the group wants to increase the number of types in public API for that? If not, then replacing `Class` by `String` argument is a lighter way to resolve the same objection.

**Comment by keilw** [comment]
It says getUnit in the PR but if they use something like `getPrefixes(Class <? extends Prefix>)` it would be great. Heartbeat etc. are extensions of the Quantity interface so even though they extend that interface and don't "implement" one they are solution-specific and neither part of the API nor RI.

**Comment by desruisseaux** [comment]
I'm not sure to understand above answer. Can we verify if we agree on the following?

1. A goal of JSR-385 is to allow the use of unit of measurement in an implementation-independent way.
2. `SystemOfUnits.getUnit(Class<? extends Quantity>)` can be used in an implementation-independent way, because there is many `Quantity` subtypes provided by the standard API.
3. There is currently no way to use `SystemOfUnitsService.getPrefixes(Class)` in an implementation-independent way.
    1. The fact that it is possible to *implement* `getPrefixes(Class)` in an implementation-independent way is irrelevant to this discussion. I'm talking about the *use* of the API.
    2. The fact that is is currently impossible to *use* `getPrefixes(Class)` in an implementation-independent way is a violation of the goal cited in point 1.
4. The implementation-independence problem can be fixed by any of the following options:
    1. Replace the `Class` argument by a `String` argument.
    2. Keep the `Class` argument but add standard `Prefix` subtypes in Unit-API.
    3. Remove completely the `getPrefixes(Class)` method because in its current state, it has no value for the users compared to invoking directly and implementation-specific method.

**Comment by keilw** [comment]
2. `SystemOfUnits.getUnit(Class<? extends Quantity>)` can be used in an implementation-independent way, because there is many Quantity subtypes provided by the standard API.

Is just not correct.

The API provides about 20-30 out of Hundreds of Quantity subtypes in the optional package. Take alone all in https://github.com/unitsofmeasurement/si-units/tree/master/quantity or https://github.com/unitsofmeasurement/uom-systems/tree/master/quantity as well as custom-defined quantity types. All of these must be used by exact class when you want to get the "system" unit that way.

**Comment by desruisseaux** [comment]
Okay, but it still 20~30 standard `Quantity` subtypes (the most frequently used ones) compared to zero standard `Prefix` subtypes. So it still possible to use `getUnit(Class)` in an implementation-independent way maybe 90% of the time, compared to never for `getPrefix(Class)`.

**Comment by keilw** [comment]
I do not see a way to add a standard prefix implementation because 
```
/**
   * Returns the corresponding {@link UnitConverter}.
   *
   * @return the unit converter.
   */
  public UnitConverter getConverter();
```
Cannot be implemented in an implementation-neutral way. It requires dozens of classes like AbstractConverter that are interconnected.

The only way of doing it would be if fe stuck to a definition much like UCAR Units [Prefix](https://github.com/ctrueden/ucar-units/blob/master/src/main/java/ucar/units/Prefix.java) Then the API could hold at least MetricPrefix and [BinaryPrefix](https://github.com/unitsofmeasurement/uom-lib/blob/master/common/src/main/java/tech/uom/lib/common/BinaryPrefix.java) the latter was declared and used in a similar way ever since JSR 363. So adding these two covering not just 60-70% (I highly doubt it is 90, take all the Scientific use cases in need of UCUM or SI with quantities the API does not define or `BIT` and `BYTE` with the `Information` quantity) but between 90 and 99% of all prefixes could be possible ;-) 

WDYT? 
Does the definition of a prefix require a `UnitConverter` for the best possible flexibility or would a factor similar to how UCAR did it be enough?

**Comment by keilw** [comment]
[The Wikipedia definition](https://en.wikipedia.org/wiki/Unit_prefix) we also refer in the JavaDoc says
> A unit prefix is a specifier or mnemonic that is prepended to units of measurement to indicate multiples or fractions of the units.

**Comment by keilw** [comment]
If there are any further arguments on `Prefix.getConverter()` vs. other methods like getValue() etc. please put it in https://github.com/unitsofmeasurement/unit-api/issues/87

**Comment by dautelle** [comment]
I don't think prefixes should be linked / accessed through the system of units, their purpose is for formatting only and they are unambiguous regardless of the system of units implementation. 

It is true that the SI standard defines the metric prefixes, but nothing prevents me from using metric prefixes with non-si units, e.g. KILO(LITER)

For me, prefixes are utility functions, e.g. KILO(METER) is equivalent to METER.multiply(1000)

The fact that KILO(METER) is represented as "km" (or "kilometer(s)") is up to the UnitFormat class.

In others words, a Prefix class is unnecessary. 

But a Metric and Binary utility classes makes sense in the API (both holding static methods only).
``
public class Metric {
     public static <Q> Unit<Q> KILO(Unit<Q> u) return u.multiply(1000);
     ...
} 
``

**Comment by andi-huber** [comment]
When using Java's ServiceLoader one does not have to utilize CDI or reflections.org, as long as implementing libraries conform to the Service-Loading mechanism as introduced with Java 7. I'm not sure how OSGi behaves in this context.

Anyway, what I wanted to point out is, that as soon as an API provides enumeration of all classes on the 'current' class-path that implement eg the Prefix interface, any use of these discovered classes can be done in an implementation-agnostic way. 

This could ease the main objection for using getPrefixes with a class argument as @desruisseaux pointed out.

**Comment by desruisseaux** [comment]
For the record, the use of `ServiceLoader` for discovering the classes provided by the implementor help, but does not tell us which class is for SI prefixes, which class is for binary prefixes, _etc._ unless we agree on some convention (naming or other).

I agree with @dautelle that prefixes are mostly a formatting things and wonder why we are trying to put them in the API in the first place?

**Comment by desruisseaux** [comment]
Indeed compilation fails on Java 9, but can easily be fixed without changing the method signature. Before doing so: do we still need this `getPrefixes(Class)` method now that users can do `MetricPrefix.values()` or `BinaryPrefix.values()`?

**Comment by keilw** [comment]
I think we should discuss if there's an easy and useful way to programatically explore such classes/interfaces. If that is someting for the service, then passing one of these classes makes sense, If it turns out to be cumbersome or we don't find a useful approach, then we might leave that method.
