### ISSUE TITLE
Would it make sense to add Level to the quantity package here?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#92]
Would it make sense to add the `Level` quantity, currently in [systems-quantity](https://github.com/unitsofmeasurement/uom-systems/blob/master/quantity/src/main/java/systems/uom/quantity/Level.java) here under the `quantity` package? As https://github.com/unitsofmeasurement/si-units/issues/47 raises a need to factor it out of **uom-systems** because the `NonSI` class is meant to complement `SI` in **si-units** for Non-SI units accepted with the SI, we should at least move `Level` to si-quantity, so the question is, whether it makes sense or wastes space to put it into the API? Compared to other new API elements it does not seem to be massive (adding `320 bytes` to the JAR) and `quantity` is an optional package that very resource constraint environments could leave out.

**Comment by keilw** [comment]
@unitsofmeasurement/experts, @unitsofmeasurement/contributors What is your preference? TIA, Werner

**Comment by desruisseaux** [comment]
Maybe if the current `Level` javadoc were updated with an example of how it relates to Bel (as an example), it would help to get a better idea? The weight I worry about is not the 320 bytes, but more about the conceptual weight of the API.

**Comment by keilw** [comment]
I have no strong preference here. My gut-feeling also suggests maybe leave it to SI here as well.

**Comment by keilw** [comment]
I voted on B now. Since the ISQ defines [Level](https://en.wikipedia.org/wiki/International_System_of_Quantities#Level) it is generally intended for use with ISO 80000, etc. but `BEL` or `DECIBEL` being permitted with the SI as well means, it should be in SI Quantities. I take @desruisseaux remarks as leaning more towards B as well? Would be nice to have at least a third @unitsofmeasurement/experts member confirm this if possible.

**Comment by filipvanlaenen** [comment]
I voted for option A because it seems like a conceptual thing part of the units domain, and not something connected to a system (SI or not). I can imagine that other systems may want to use the `Level` interface too. Imagine a weird system measuring lengths in a logarithmic way, shouldn't it use a `Level` interface from the unit API rather than borrowing a `Level` interface from the SI system?

On the other hand, I'm not sure I understand the `Level` interface entirely. Does e.g. the `multiply` method, inherited from the `Quantity` interface, make sense in it?

**Comment by keilw** [comment]
Thanks for voting. There is a certain point because although the [ISQ](https://en.wikipedia.org/wiki/International_System_of_Quantities) has ties to the SI system, pretty much all quantities mentioned there (derived ones are just a small subset) are in the quantity package here in the API module. Every quantity inherits the methods from `Quantity`, that includes `Dimensionless`, previously used for `NEPER`, `BEL` or `DECIBEL` in JScience. The second level of generic typing allows to define what each of these are, the UCUM system shows a couple of use cases already.

**Comment by keilw** [comment]
@andi-huber What's your opinion on this? We have 2 thumbs and one statement somewhat leaning more towards the SI module. If we get one or two extra votes, I'd love to wrap it up and refactor the `Level `interface to the desired place.

**Comment by andi-huber** [comment]
I think you all made good points here. I have no strong preference. 

Maybe go with B) for now and leave option A) as a future possibility, in case it turns out that A) makes more sense!?

**Comment by keilw** [comment]
Thanks, then based on my initial vote/thought, the concerns @desruisseaux raised here and your input we have a stronger point for B. And you're right, we could either with an MR or similar future version of the API still add it there. I'll close this issue and create an action item for si-units if it's not there already.
