### ISSUE TITLE
Update UML diagrams

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#97]
New API elements like Prefix are not documented in the EMF model.

**Comment by thodorisbais** [comment]
As far as I can make clear from our README file (and some failed trials to display EMF's uml in Intellij 😂) we do not have any stable solution to open and edit UML diagrams in Intellij, right? I invested a bit of time in making it work with IntelliJ as well but didn't succeed. I'll give it one more try somewhere next week, else I'll check with Eclipse.

**Comment by keilw** [comment]
I'm afraid IntelliJ has no such UML support as Eclipse Papyru which is Open Source and free of charge.

**Comment by thodorisbais** [comment]
I think so, too. Maybe I need to download Eclipse as well.

**Comment by keilw** [comment]
Thanks, what do you think about https://github.com/unitsofmeasurement/indriya/issues/211? I think regardless of how we name it, formatting or parsing different entries without having to recreate a new `QuantityFormat` instance for every quantity type is important. As long as the `Builder` arguments don't change, there should be no need to build another format.

**Comment by thodorisbais** [comment]
I'll do soon. It's been a hectic week with an @utrechtjug meetup, a devoxx4kids alignment, a speakers incubator evening and work, so, I first need to recover a bit :-)

**Comment by thodorisbais** [comment]
I haven't installed Eclipse yet, but given the referenced commit above, do we still need to do anything for this issue?

**Comment by thodorisbais** [comment]
Installed Eclipse and Papyrus and I'm able to see some UML, but I have a question, given the few newly referenced on this issue commits: how do we normally update the UMLs? Is it just about a reverse engineering option of Papyrus or does it require manual work?
