### ISSUE TITLE
Arithmetic operations shall obey arithmetic laws

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#99]
This issue follow #98 ("Result of A + B shall be determinist"). The `Quantity.add(Quantity)` and `Quantity.multiply(Number)` operations shall be defined by the specification in such a way that they obey at least to the following laws (_A_, _B_ and _C_ are `Quantity` instances):

* If _A_ = _B_, then _A_+_C_ = _B_+_C_.
* If _A_ = _B_, then _A_\*_n_ = _B_\*_n_ where _n_ is a number.
* _A_+_B_ = _B_+_A_ (addition commutativity).
* A + (-1 * B) = A - B

In above equations, = means "numerically equivalent": implementations are allowed to produce results in different units of measurement provided that conversion to a common unit by the `Quantity.to(Unit)` method gives the same numerical value (ignoring rounding errors).

Any proposal that do not obey above laws shall be rejected.

**Comment by kinow** [comment]
Agree to all laws. We have a forecasting project, which does calculations with temperatures (F, C, etc), wind speed (km/h, m/s, etc) are planning to switch from jscience, and these laws are a must for us.

**Comment by keilw** [comment]
JScience does everything the same way JSR 363 does, so there's nothing that prevents you from leaving a JSR that never went final to one that is, otherwise you'd have to wait at least a year till Q1 or 2 next year.

**Comment by kinow** [comment]
@keilw yup, we are already slowly moving the old code base, and now keeping an eye on the discussion here start monitoring what's on [JSR-385](https://www.jcp.org/en/jsr/detail?id=385) too.

**Comment by desruisseaux** [comment]
> JScience does everything the same way JSR 363 does

Actually JSR 363 does not do arithmetic in any particular way, since it does not specify the behavior of arithmetic operations. JScience may does everything in the same way than JSR 363 reference implementation, but this is not exactly the same. Another implementation could do arithmetic in a correct way and still be JSR 363 compliant.

**Comment by keilw** [comment]
I doubt we're ever going to enforce a particular behavior of an implementation via TCK. Since most parts of the API and JSR (363, not 275) are optional, an implementation could chose not to support it at all. Or stick to KELVIN only, so I doubt, a conversion that involves multiple units can be part of the TCK. We can mention it in the Spec/JavaDoc as mentioned for the EDR. And possibly add something like that level `enum`. Whether or not anything should be enforced in the TCK, I can't say. E.g. for the new `Prefix` having at least 2 implementations is sufficient.

**Comment by desruisseaux** [comment]
I have no objection for leaving arithmetic operations optional, and no problem neither for allowing implementations to return result in Kelvin or whatever units they want, as long as they are equivalent to expected result.

TCK could test arithmetic operations only if the implementation declares to support them. When checking the result of arithmetic operations, TCK should check if the actual result is _equivalent_ to the expected result, not necessarily _equal_ (with equivalence and equality defined [here](https://github.com/unitsofmeasurement/unit-api/wiki/Arithmetic-operations-on-Quantity)).

**Comment by desruisseaux** [comment]
Following phone call on Thursday 21th 2018, I believe there is an agreement that arithmetic operations shall obey to arithmetic laws. Closing this issue as _"accepted in principle"_. Concrete action will be a merge request with Javadoc updates along the line of the [Arithmetic operations shall obey arithmetic laws](https://github.com/unitsofmeasurement/unit-api/issues/99) wiki page. See #95 for discussion.

**Comment by keilw** [comment]
Whether we could enforce it in the TCK, that's another question. As long as we make recommendations in the Spec and JavaDoc only without longer-term API additions, I don't think the TCK could do such strict checks.
